FROM python:3.11-slim
WORKDIR /app
ENV PYTHONPATH=/app
ENV PYTHONPATH=/app
RUN pip install --no-cache-dir google-cloud-storage feedparser Flask gunicorn toml
COPY cloudrun/. .
CMD ["sh", "-c", "python -m gunicorn --bind 0.0.0.0:$PORT fetch_news_runner:app"]
