#!/usr/bin/env python3
from __future__ import annotations

import argparse
import collections
import datetime as dt
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
DAILY_PATH = DOCS_DIR / "REPO_HISTORY_DAILY_ANNEX.md"
WEEKLY_PATH = DOCS_DIR / "REPO_HISTORY_WEEKLY_ANNEX.md"
MAIN_MINUTES_PATH = DOCS_DIR / "REPO_HISTORY_MINUTES.md"


@dataclass(frozen=True)
class CommitEntry:
    date: str
    short_hash: str
    subject: str
    files: tuple[str, ...]


def _git_history() -> list[CommitEntry]:
    out = subprocess.check_output(
        [
            "git",
            "log",
            "--reverse",
            "--date=short",
            "--pretty=format:@@@%ad\t%h\t%s",
            "--name-only",
        ],
        text=True,
        cwd=ROOT,
    )
    entries: list[CommitEntry] = []
    current: tuple[str, str, str] | None = None
    files: list[str] = []

    for line in out.splitlines() + ["@@@END\t\t"]:
        if line.startswith("@@@"):
            if current is not None:
                date, short_hash, subject = current
                entries.append(
                    CommitEntry(
                        date=date,
                        short_hash=short_hash,
                        subject=subject,
                        files=tuple(files),
                    )
                )
            if line.startswith("@@@END"):
                break
            current = tuple(line[3:].split("\t", 2))  # type: ignore[assignment]
            files = []
            continue

        if line.strip():
            files.append(line.strip())

    return entries


def _top_roots(entries: Iterable[CommitEntry], limit: int = 3) -> str:
    counts: collections.Counter[str] = collections.Counter()
    for entry in entries:
        for path in entry.files:
            counts[path.split("/", 1)[0] if "/" in path else path] += 1
    return ", ".join(root for root, _ in counts.most_common(limit)) or "-"


def _subject_summary(entries: Iterable[CommitEntry], limit: int = 2) -> str:
    subjects = [entry.subject.replace("|", "/").replace("\n", " ") for entry in entries if not entry.subject.startswith("Merge ")]
    if not subjects:
        return "merge-only day"
    summary = " / ".join(subjects[:limit])
    if len(subjects) > limit:
        summary += f" / +{len(subjects) - limit} more"
    return summary


def _render_daily(entries: list[CommitEntry]) -> str:
    by_date: dict[str, list[CommitEntry]] = collections.defaultdict(list)
    for entry in entries:
        by_date[entry.date].append(entry)

    by_month: dict[str, list[tuple[str, list[CommitEntry]]]] = collections.OrderedDict()
    for date in sorted(by_date):
        by_month.setdefault(date[:7], []).append((date, by_date[date]))

    lines = [
        "# QuantRabbit 開発履歴 日次 Annex",
        "",
        f"- Generated by `scripts/{Path(__file__).name}`. 手修正より再生成を優先してください。",
        f"- この annex は [REPO_HISTORY_MINUTES.md](./{MAIN_MINUTES_PATH.name}) の詳細版で、active date ごとの raw ledger です。",
        "- 各行の `主な領域` は当日の変更ファイルの top-level path 上位 3 件です。",
        "- `代表変更` は merge commit を除いた先頭 2 件を並べ、残件数は `+N more` で表記しています。",
        "",
    ]

    for month, items in by_month.items():
        lines.extend(
            [
                f"## {month}",
                "",
                "| Date | Commits | 主な領域 | 代表変更 |",
                "| --- | ---: | --- | --- |",
            ]
        )
        for date, day_entries in items:
            lines.append(
                f"| {date} | {len(day_entries)} | {_top_roots(day_entries)} | {_subject_summary(day_entries)} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _week_start(date_str: str) -> dt.date:
    current = dt.date.fromisoformat(date_str)
    return current - dt.timedelta(days=current.weekday())


def _render_weekly(entries: list[CommitEntry]) -> str:
    by_week: dict[dt.date, list[CommitEntry]] = collections.defaultdict(list)
    for entry in entries:
        by_week[_week_start(entry.date)].append(entry)

    by_year: dict[int, list[tuple[dt.date, list[CommitEntry]]]] = collections.OrderedDict()
    for start in sorted(by_week):
        by_year.setdefault(start.isocalendar().year, []).append((start, by_week[start]))

    lines = [
        "# QuantRabbit 開発履歴 週次 Annex",
        "",
        f"- Generated by `scripts/{Path(__file__).name}`. 手修正より再生成を優先してください。",
        f"- この annex は [REPO_HISTORY_MINUTES.md](./{MAIN_MINUTES_PATH.name}) と [REPO_HISTORY_DAILY_ANNEX.md](./{DAILY_PATH.name}) の中間粒度です。",
        "- 週の区切りは `月曜始まり / 日曜終わり` です。",
        "- `代表変更` はその週の merge を除いた先頭 2 件を並べ、残件数は `+N more` で表記しています。",
        "",
    ]

    for year, items in by_year.items():
        lines.extend(
            [
                f"## {year}",
                "",
                "| ISO Week | Range | Commits | 主な領域 | 代表変更 |",
                "| --- | --- | ---: | --- | --- |",
            ]
        )
        for start, week_entries in items:
            end = start + dt.timedelta(days=6)
            iso = start.isocalendar()
            label = f"{iso.year}-W{iso.week:02d}"
            lines.append(
                "| "
                + f"{label} | {start.isoformat()}〜{end.isoformat()} | {len(week_entries)} | "
                + f"{_top_roots(week_entries)} | {_subject_summary(week_entries)} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _write_outputs(render_daily: bool, render_weekly: bool) -> None:
    history = _git_history()
    if render_daily:
        DAILY_PATH.write_text(_render_daily(history), encoding="utf-8")
    if render_weekly:
        WEEKLY_PATH.write_text(_render_weekly(history), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate repository history annex markdown files.")
    parser.add_argument(
        "--which",
        choices=("daily", "weekly", "all"),
        default="all",
        help="Which annex to generate (default: all).",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated markdown into docs/ instead of printing to stdout.",
    )
    args = parser.parse_args()

    history = _git_history()
    want_daily = args.which in {"daily", "all"}
    want_weekly = args.which in {"weekly", "all"}

    if args.write:
        if want_daily:
            DAILY_PATH.write_text(_render_daily(history), encoding="utf-8")
        if want_weekly:
            WEEKLY_PATH.write_text(_render_weekly(history), encoding="utf-8")
        return 0

    if want_daily:
        print(_render_daily(history), end="")
    if want_daily and want_weekly:
        print()
    if want_weekly:
        print(_render_weekly(history), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
