#!/usr/bin/env bash

# Shared live-runtime evidence/report drift contract. Keep both deployment sync
# and the live wrapper on this one predicate so one cannot silently reject a
# runtime artifact that the other explicitly permits.
qr_is_runtime_drift_path() {
  local path="$1"
  case "$path" in
    docs/*_report.md|\
docs/*_report.close_reentry.md|\
docs/guardian_action_review.md|\
docs/as_lane_candidate_board.md|\
docs/as_proof_pack_queue.md|\
docs/audjpy_short_breakout_failure_limit_proof_pack.md|\
docs/audjpy_short_breakout_failure_repair_proof.md|\
docs/active_trader_contract.md|\
docs/active_opportunity_board.md|\
docs/entry_frequency_recovery_report.md|\
docs/forecast_pattern_refresh_report.md|\
docs/range_rail_geometry_repair_report.md|\
docs/eurusd_short_breakout_failure_evidence_acquisition_plan.md|\
docs/eurusd_short_breakout_failure_legacy_sample_search.md|\
docs/eurusd_short_breakout_failure_limit_s5_bidask_replay.md|\
docs/eurusd_short_breakout_failure_limit_sample_mining.md|\
docs/eurusd_short_breakout_failure_market_stop_vehicle_diagnosis.md|\
docs/eurusd_short_breakout_failure_proof_floor_update.md|\
docs/eurusd_short_breakout_failure_scout_plan.md|\
docs/eurusd_short_breakout_failure_spread_slippage_proof.md|\
docs/eurusd_short_breakout_failure_stop_harvest_replay.md|\
docs/eurusd_short_breakout_failure_vehicle_split_diagnosis.md|\
docs/historical_only_to_fresh_proof_replay.md|\
docs/manual_eurusd_tp_replacement_provenance.md|\
docs/non_eurusd_live_grade_frontier.md|\
docs/non_eurusd_proof_lane_mapper.md|\
docs/operator_review_report.md|\
docs/portfolio_4x_path_planner.md|\
docs/post_gate_capture_economics_decomposition.md|\
docs/post_gate_expectancy_gap_trace.md|\
docs/post_gate_gap_family_repair_table.md|\
docs/profitability_acceptance_blocker_reconciliation.md|\
docs/remaining_profitability_p0_decomposition.md|\
docs/rolling_30d_4x_firepower_board.md|\
data/guardian_trigger_contract.json|\
data/guardian_receipt_consumption.json|\
data/guardian_receipt_operator_review.json|\
data/as_lane_candidate_board.json|\
data/as_proof_pack_queue.json|\
data/audjpy_short_breakout_failure_limit_proof_pack.json|\
data/audjpy_short_breakout_failure_repair_proof.json|\
data/active_trader_contract.json|\
data/active_opportunity_board.json|\
data/entry_frequency_recovery.json|\
data/forecast_pattern_refresh.json|\
data/range_rail_geometry_repair.json|\
data/eurusd_short_breakout_failure_evidence_acquisition_plan.json|\
data/eurusd_short_breakout_failure_legacy_sample_search.json|\
data/eurusd_short_breakout_failure_limit_s5_bidask_replay.json|\
data/eurusd_short_breakout_failure_limit_sample_mining.json|\
data/eurusd_short_breakout_failure_market_stop_vehicle_diagnosis.json|\
data/eurusd_short_breakout_failure_proof_floor_update.json|\
data/eurusd_short_breakout_failure_scout_plan.json|\
data/eurusd_short_breakout_failure_spread_slippage_proof.json|\
data/eurusd_short_breakout_failure_stop_harvest_replay.json|\
data/eurusd_short_breakout_failure_vehicle_split_diagnosis.json|\
data/harvest_live_grade_path.json|\
data/historical_only_to_fresh_proof_replay.json|\
data/manual_eurusd_tp_replacement_provenance.json|\
data/non_eurusd_live_grade_frontier.json|\
data/non_eurusd_proof_lane_mapper.json|\
data/operator_review_report.json|\
data/portfolio_4x_path_planner.json|\
data/post_gate_capture_economics_decomposition.json|\
data/post_gate_expectancy_gap_trace.json|\
data/post_gate_gap_family_repair_table.json|\
data/payoff_shape_diagnosis.json|\
data/profitability_acceptance_blocker_reconciliation.json|\
data/remaining_profitability_p0_decomposition.json|\
data/rolling_30d_4x_firepower_board.json|\
data/predictive_scout_forward_proof.json|\
data/technical_forecast_forward_shadow.json|\
data/technical_forecast_forward_shadow_ledger.jsonl|\
data/technical_forecast_forward_outcome_ledger.jsonl|\
data/technical_forecast_forward_scorecard.json|\
data/hierarchical_bot_regime.json|\
data/ai_regime_supervision.json|\
data/position_guardian_all_pair_m1.json|\
data/position_guardian_slow_retention.json|\
docs/position_guardian_all_pair_m1_report.md|\
data/fast_bot_shadow.json|\
data/fast_bot_shadow_ledger.jsonl|\
data/fast_bot_episode_state.json|\
data/fast_bot_episode_state.json.pending|\
data/fast_bot_episode_ledger.jsonl|\
data/fast_bot_episode_vehicle_ledger.jsonl|\
data/fast_bot_episode_outcome_ledger.jsonl|\
data/fast_bot_episode_scorecard.json|\
data/fast_bot_episode_truth.lock|\
data/.fast_bot_episode_vehicle_ledger.jsonl.*.tmp|\
data/.fast_bot_episode_outcome_ledger.jsonl.*.tmp|\
data/.fast_bot_episode_scorecard.json.*.tmp|\
data/fast_bot_episode_handoffs/.owner.json|\
data/fast_bot_episode_handoffs/.metadata.lock|\
data/fast_bot_episode_handoffs/.worker.lock|\
data/fast_bot_episode_handoffs/.handoff-*.tmp|\
data/fast_bot_episode_handoffs/handoff-*.json|\
data/fast_bot_episode_sources/.owner.json|\
data/fast_bot_episode_sources/*.json.gz|\
data/fast_bot_outcome_ledger.jsonl|\
data/fast_bot_scorecard.json|\
data/fast_bot_learning_shadow.json|\
data/fast_bot_learning_seat_ledger.jsonl|\
data/fast_bot_learning_outcome_ledger.jsonl|\
data/fast_bot_learning_due_cursor.json|\
data/fast_bot_learning_scorecard.json|\
data/contextual_technical_240m_forward_shadow.json|\
data/contextual_technical_240m_forward_shadow_ledger.jsonl|\
data/contextual_technical_240m_forward_outcome_ledger.jsonl|\
data/contextual_technical_240m_forward_scorecard.json|\
data/trader_goal_loop_orchestrator.json)
      return 0
      ;;
  esac
  return 1
}
