"""Independent economic replay for the DOJO strategy-worker smoke.

Only two inputs are trusted: an exactly sealed USD_JPY M1 corpus and a
hash-chained sequence of cursor-bound ``ACTION_INTENT`` records.  Broker fill,
exit, financing, margin, and period-end numbers are derived here; worker
ledger P/L and terminal account declarations are deliberately not accepted as
inputs.

This is an independent reducer, not a wrapper around :mod:`virtual_broker`.
It intentionally remains self-attested diagnostic evidence until the action
intents are regenerated by a pinned bot runtime and the seals have an external
monotonic witness.  The exact corpus bytes are checked here, but the collector's
market-coverage receipt is not yet a parent of the replay result.  In particular,
this module does not make an existing cursor-less worker ledger scoreable.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any


ACTION_INTENT_CONTRACT = "QR_DOJO_WORKER_ACTION_INTENT_V1"
ECONOMIC_REPLAY_CONTRACT = "QR_DOJO_WORKER_ECONOMIC_REPLAY_V1"
EVIDENCE_TIER = "SELF_ATTESTED_UNVERIFIED_DIAGNOSTIC"
ACTION_POSITION = "AFTER_PHASE_OUTCOMES"
PAIR = "USD_JPY"
GRANULARITY = "M1"
PRICE_COMPONENT = "BA"
LEVERAGE_DEFAULT = 25.0
CLOSEOUT_USAGE = 1.0
_ZERO_SHA = "0" * 64
_HEX64 = re.compile(r"[0-9a-f]{64}")
_IDENTIFIER = re.compile(r"[A-Za-z0-9][A-Za-z0-9._:-]{0,127}")
_DECIMAL = re.compile(r"(?:0|[1-9][0-9]*)\.[0-9]+")
_TIME = re.compile(r"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(0+))?Z")
_PHASE_KEYS = {
    "OHLC": (("O", "o"), ("H", "h"), ("L", "l"), ("C", "c")),
    "OLHC": (("O", "o"), ("L", "l"), ("H", "h"), ("C", "c")),
}
_ACTION_PARAMETER_KEYS = {
    "MARKET": frozenset({"pair", "side", "units", "tp_pips", "sl_pips"}),
    "LIMIT": frozenset(
        {"pair", "side", "units", "price", "tp_pips", "sl_pips"}
    ),
    "STOP": frozenset(
        {"pair", "side", "units", "price", "tp_pips", "sl_pips"}
    ),
    "CANCEL": frozenset({"order_id"}),
    "CLOSE": frozenset({"trade_id", "units"}),
    "SET_EXIT": frozenset({"trade_id", "tp_price", "sl_price"}),
}
_INTENT_KEYS = frozenset(
    {
        "contract",
        "schema_version",
        "candidate_id",
        "owner_id",
        "sequence",
        "cursor",
        "action",
        "parameters",
        "previous_action_sha256",
        "action_sha256",
    }
)


class DojoWorkerEconomicReplayError(ValueError):
    """A sealed source, action transcript, or economic invariant failed."""


@dataclass(frozen=True)
class _Quote:
    epoch: int
    phase: str
    bid: float
    ask: float
    ts: str


@dataclass
class _Order:
    order_id: str
    owner_id: str
    pair: str
    side: str
    units: float
    trigger_price: float
    tp_pips: float | None
    sl_pips: float | None
    kind: str


@dataclass
class _Position:
    trade_id: str
    owner_id: str
    pair: str
    side: str
    units: float
    entry_price: float
    opened_ts: str
    tp_price: float | None
    sl_price: float | None


def canonical_sha256(value: Any) -> str:
    """Return the canonical digest used by the action and result seals."""

    try:
        encoded = json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise DojoWorkerEconomicReplayError("value is not canonical JSON") from exc
    return hashlib.sha256(encoded).hexdigest()


def seal_action_intents(
    *,
    candidate_id: str,
    owner_id: str,
    intents: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    """Build one append-only action chain from unsealed intent bodies.

    Each body must contain exactly ``cursor``, ``action``, and ``parameters``.
    The replay verifier performs the economic and cursor validation; this
    helper only creates the immutable envelope.
    """

    _validate_identifier("candidate_id", candidate_id)
    _validate_identifier("owner_id", owner_id)
    if isinstance(intents, (str, bytes)) or not isinstance(intents, Sequence):
        raise DojoWorkerEconomicReplayError("intents must be a sequence")
    sealed: list[dict[str, Any]] = []
    previous = _ZERO_SHA
    for index, raw in enumerate(intents, start=1):
        item = _mapping(raw, f"intent[{index}]")
        if set(item) != {"cursor", "action", "parameters"}:
            raise DojoWorkerEconomicReplayError("unsealed intent schema is not exact")
        body = {
            "contract": ACTION_INTENT_CONTRACT,
            "schema_version": 1,
            "candidate_id": candidate_id,
            "owner_id": owner_id,
            "sequence": index,
            "cursor": item["cursor"],
            "action": item["action"],
            "parameters": item["parameters"],
            "previous_action_sha256": previous,
        }
        record = {**body, "action_sha256": canonical_sha256(body)}
        sealed.append(record)
        previous = record["action_sha256"]
    return sealed


def replay_worker_economics(
    *,
    corpus_root: Path,
    expected_corpus: Mapping[str, Any],
    window_start_utc: str,
    window_end_utc: str,
    intrabar: str,
    candidate_id: str,
    owner_id: str,
    actions: Sequence[Mapping[str, Any]],
    initial_balance_jpy: float,
    slippage_pips_per_fill: float,
    financing_pips_per_day: float,
    leverage: float = LEVERAGE_DEFAULT,
) -> dict[str, Any]:
    """Recompute one worker cell from sealed quote bytes and action intents."""

    _validate_identifier("candidate_id", candidate_id)
    _validate_identifier("owner_id", owner_id)
    balance = _finite("initial_balance_jpy", initial_balance_jpy, positive=True)
    slippage = _finite(
        "slippage_pips_per_fill", slippage_pips_per_fill, non_negative=True
    )
    financing = _finite(
        "financing_pips_per_day", financing_pips_per_day, non_negative=True
    )
    leverage_value = _finite("leverage", leverage, positive=True)
    if intrabar not in _PHASE_KEYS:
        raise DojoWorkerEconomicReplayError("intrabar must be OHLC or OLHC")
    start = _parse_window_time(window_start_utc, "window_start_utc")
    end = _parse_window_time(window_end_utc, "window_end_utc")
    if end <= start:
        raise DojoWorkerEconomicReplayError("replay window must be positive")

    quotes = _load_quote_phases(
        Path(corpus_root), expected_corpus, start=start, end=end, intrabar=intrabar
    )
    normalized_actions = _validate_action_chain(
        actions,
        candidate_id=candidate_id,
        owner_id=owner_id,
        intrabar=intrabar,
        quote_cursors={(quote.epoch, quote.phase) for quote in quotes},
    )
    reducer = _EconomicReducer(
        owner_id=owner_id,
        balance_jpy=balance,
        slippage_pips=slippage,
        financing_pips_per_day=financing,
        leverage=leverage_value,
    )
    by_cursor: dict[tuple[int, str], list[Mapping[str, Any]]] = {}
    for action in normalized_actions:
        cursor = action["cursor"]
        by_cursor.setdefault((cursor["epoch"], cursor["phase"]), []).append(action)

    trace = hashlib.sha256()
    for quote in quotes:
        trace.update(
            _canonical_json_bytes(
                {
                    "epoch": quote.epoch,
                    "phase": quote.phase,
                    "quotes": [
                        {"pair": PAIR, "bid": quote.bid, "ask": quote.ask, "ts": quote.ts}
                    ],
                }
            )
            + b"\n"
        )
        reducer.process_quote(quote)
        for action in by_cursor.get((quote.epoch, quote.phase), []):
            reducer.apply_action(action, quote)

    period_end = reducer.settle_period_end(quotes[-1])
    account = reducer.account(quotes[-1])
    action_tip = (
        normalized_actions[-1]["action_sha256"] if normalized_actions else _ZERO_SHA
    )
    first_cursor = {"epoch": quotes[0].epoch, "phase": quotes[0].phase}
    last_cursor = {"epoch": quotes[-1].epoch, "phase": quotes[-1].phase}
    entries = reducer.entries
    resolved = reducer.resolved_exits
    terminal_net = reducer.balance_jpy - balance
    result: dict[str, Any] = {
        "contract": ECONOMIC_REPLAY_CONTRACT,
        "schema_version": 1,
        "evidence_tier": EVIDENCE_TIER,
        "promotion_eligible": False,
        "promotion_blockers": [
            "ACTION_INTENTS_NOT_REGENERATED_FROM_PINNED_BOT",
            "SOURCE_COVERAGE_RECEIPT_NOT_BOUND",
            "EXTERNAL_MONOTONIC_WITNESS_ABSENT",
        ],
        "candidate_id": candidate_id,
        "owner_id": owner_id,
        "intrabar": intrabar,
        "window": {
            "start_utc": window_start_utc,
            "end_utc": window_end_utc,
        },
        "corpus_sha256": expected_corpus["corpus_sha256"],
        "action_count": len(normalized_actions),
        "action_chain_tip_sha256": action_tip,
        "feed_trace_sha256": trace.hexdigest(),
        "quote_batch_count": len(quotes),
        "first_cursor": first_cursor,
        "last_cursor": last_cursor,
        "mechanics": {
            "pair": PAIR,
            "granularity": GRANULARITY,
            "price_component": PRICE_COMPONENT,
            "initial_balance_jpy": balance,
            "slippage_pips_per_fill": slippage,
            "financing_pips_per_day": financing,
            "leverage": leverage_value,
            "closeout_usage": CLOSEOUT_USAGE,
            "action_position": ACTION_POSITION,
            "period_end_policy": "CANCEL_ORDERS_THEN_CLOSE_TRADES_AT_LAST_QUOTE",
        },
        "events": reducer.events,
        "event_chain_tip_sha256": reducer.event_tip,
        "period_end": period_end,
        "account": account,
        "score": {
            "entries": entries,
            "resolved_exits": resolved,
            "wins": reducer.wins,
            "win_rate_resolved": round(reducer.wins / resolved, 6)
            if resolved
            else None,
            "margin_closeouts": reducer.margin_closeouts,
            "gross_pl_jpy": round(reducer.gross_pl_jpy, 2),
            "financing_jpy": round(reducer.financing_jpy, 2),
            "realized_net_jpy": round(terminal_net, 2),
            "terminal_net_jpy": round(terminal_net, 2),
            "final_balance_jpy": account["balance_jpy"],
            "final_equity_jpy": account["equity_jpy"],
            "terminal_resolved": (
                account["open_positions"] == 0 and account["resting_orders"] == 0
            ),
        },
    }
    result["replay_sha256"] = canonical_sha256(result)
    return result


class _EconomicReducer:
    def __init__(
        self,
        *,
        owner_id: str,
        balance_jpy: float,
        slippage_pips: float,
        financing_pips_per_day: float,
        leverage: float,
    ) -> None:
        self.owner_id = owner_id
        self.balance_jpy = balance_jpy
        self.slippage_pips = slippage_pips
        self.financing_pips_per_day = financing_pips_per_day
        self.leverage = leverage
        self.orders: dict[str, _Order] = {}
        self.positions: dict[str, _Position] = {}
        self.last_quote: _Quote | None = None
        self._id_sequence = 0
        self.events: list[dict[str, Any]] = []
        self.event_tip = _ZERO_SHA
        self.entries = 0
        self.resolved_exits = 0
        self.wins = 0
        self.margin_closeouts = 0
        self.gross_pl_jpy = 0.0
        self.financing_jpy = 0.0

    def _next_id(self, prefix: str) -> str:
        self._id_sequence += 1
        return f"{prefix}{self._id_sequence:06d}"

    def _emit(
        self, event: str, payload: Mapping[str, Any], *, cursor_position: str
    ) -> None:
        if self.last_quote is None:
            raise DojoWorkerEconomicReplayError("event has no causal quote")
        body = {
            "sequence": len(self.events) + 1,
            "cursor": {
                "epoch": self.last_quote.epoch,
                "phase": self.last_quote.phase,
                "position": cursor_position,
            },
            "event": event,
            "payload": dict(payload),
            "previous_event_sha256": self.event_tip,
        }
        record = {**body, "event_sha256": canonical_sha256(body)}
        self.events.append(record)
        self.event_tip = record["event_sha256"]

    def account(self, quote: _Quote) -> dict[str, Any]:
        equity = self.balance_jpy
        long_units = 0.0
        short_units = 0.0
        accrued_financing = 0.0
        for position in self.positions.values():
            mark = quote.bid if position.side == "LONG" else quote.ask
            difference = (
                mark - position.entry_price
                if position.side == "LONG"
                else position.entry_price - mark
            )
            financing = self._financing(position, quote.ts)
            equity += difference * position.units - financing
            accrued_financing += financing
            if position.side == "LONG":
                long_units += position.units
            else:
                short_units += position.units
        mid = (quote.bid + quote.ask) / 2.0
        margin = max(long_units, short_units) * mid / self.leverage
        usage = margin / equity if equity > 0 else 999.0
        return {
            "balance_jpy": round(self.balance_jpy, 2),
            "equity_jpy": round(equity, 2),
            "margin_used_jpy": round(margin, 2),
            "margin_usage": round(usage, 6),
            "accrued_financing_jpy": round(accrued_financing, 2),
            "open_positions": len(self.positions),
            "resting_orders": len(self.orders),
        }

    def _margin_headroom_ok(self, side: str, units: float, quote: _Quote) -> bool:
        account = self.account(quote)
        long_units = sum(
            item.units for item in self.positions.values() if item.side == "LONG"
        )
        short_units = sum(
            item.units for item in self.positions.values() if item.side == "SHORT"
        )
        old_units = max(long_units, short_units)
        if side == "LONG":
            long_units += units
        else:
            short_units += units
        mid = (quote.bid + quote.ask) / 2.0
        old_margin = old_units * mid / self.leverage
        new_margin = max(long_units, short_units) * mid / self.leverage
        new_total = account["margin_used_jpy"] - old_margin + new_margin
        return new_total <= account["equity_jpy"]

    def process_quote(self, quote: _Quote) -> None:
        self.last_quote = quote
        for order_id in list(self.orders):
            order = self.orders[order_id]
            filled_price: float | None = None
            if order.kind == "LIMIT":
                if order.side == "LONG" and quote.ask <= order.trigger_price:
                    filled_price = min(order.trigger_price, quote.ask)
                elif order.side == "SHORT" and quote.bid >= order.trigger_price:
                    filled_price = max(order.trigger_price, quote.bid)
            else:
                if order.side == "LONG" and quote.ask >= order.trigger_price:
                    filled_price = max(order.trigger_price, quote.ask)
                elif order.side == "SHORT" and quote.bid <= order.trigger_price:
                    filled_price = min(order.trigger_price, quote.bid)
            if filled_price is None:
                continue
            applied_slippage = 0.0
            if self.slippage_pips > 0:
                stressed = _round_price(
                    filled_price + self.slippage_pips * 0.01
                    if order.side == "LONG"
                    else filled_price - self.slippage_pips * 0.01
                )
                filled_price = (
                    min(order.trigger_price, stressed)
                    if order.kind == "LIMIT" and order.side == "LONG"
                    else max(order.trigger_price, stressed)
                    if order.kind == "LIMIT"
                    else stressed
                )
                if filled_price <= 0:
                    raise DojoWorkerEconomicReplayError(
                        "slippage produced a non-positive entry price"
                    )
                observed = quote.ask if order.side == "LONG" else quote.bid
                applied_slippage = abs(filled_price - observed) / 0.01
            if not self._margin_headroom_ok(order.side, order.units, quote):
                del self.orders[order_id]
                self._emit(
                    "ORDER_REJECTED_INSUFFICIENT_MARGIN",
                    {"order_id": order_id, "pair": PAIR},
                    cursor_position="PHASE_OUTCOMES",
                )
                continue
            trade_id = self._next_id("T")
            tp, sl = _entry_exits(
                order.side, filled_price, order.tp_pips, order.sl_pips
            )
            self.positions[trade_id] = _Position(
                trade_id=trade_id,
                owner_id=order.owner_id,
                pair=PAIR,
                side=order.side,
                units=order.units,
                entry_price=filled_price,
                opened_ts=quote.ts,
                tp_price=tp,
                sl_price=sl,
            )
            del self.orders[order_id]
            self.entries += 1
            # VirtualBroker's established ledger schema calls both resting
            # LIMIT and STOP entry fills FILL_LIMIT.  price_protection and
            # order_kind preserve the economically important distinction.
            self._emit(
                "FILL_LIMIT",
                {
                    "order_id": order_id,
                    "trade_id": trade_id,
                    "owner_id": order.owner_id,
                    "pair": PAIR,
                    "side": order.side,
                    "units": order.units,
                    "price": filled_price,
                    "tp": tp,
                    "sl": sl,
                    "quote": _quote_payload(quote),
                    "slippage_pips": self.slippage_pips,
                    "applied_slippage_pips": round(applied_slippage, 8),
                    "price_protection": order.kind == "LIMIT",
                    "order_kind": order.kind,
                },
                cursor_position="PHASE_OUTCOMES",
            )

        for trade_id in list(self.positions):
            position = self.positions[trade_id]
            exit_price: float | None = None
            reason: str | None = None
            if position.side == "LONG":
                if position.sl_price is not None and quote.bid <= position.sl_price:
                    exit_price, reason = min(position.sl_price, quote.bid), "SL"
                elif position.tp_price is not None and quote.bid >= position.tp_price:
                    exit_price, reason = position.tp_price, "TP"
            else:
                if position.sl_price is not None and quote.ask >= position.sl_price:
                    exit_price, reason = max(position.sl_price, quote.ask), "SL"
                elif position.tp_price is not None and quote.ask <= position.tp_price:
                    exit_price, reason = position.tp_price, "TP"
            if exit_price is None or reason is None:
                continue
            applied_slippage = 0.0
            if reason == "SL":
                stressed = self._adverse_exit_price(position.side, exit_price)
                applied_slippage = abs(stressed - exit_price) / 0.01
                exit_price = stressed
            else:
                exit_price = _round_price(exit_price)
            self._realize(
                position,
                units=position.units,
                price=exit_price,
                quote=quote,
                event=f"EXIT_{reason}",
                cursor_position="PHASE_OUTCOMES",
                extra={
                    "applied_slippage_pips": round(applied_slippage, 8),
                    "price_protection": reason == "TP",
                },
            )
        self._enforce_margin(quote)

    def apply_action(self, action: Mapping[str, Any], quote: _Quote) -> None:
        if self.last_quote != quote:
            raise DojoWorkerEconomicReplayError("action quote cursor is not current")
        name = action["action"]
        parameters = action["parameters"]
        if name == "MARKET":
            side = parameters["side"]
            units = parameters["units"]
            if not self._margin_headroom_ok(side, units, quote):
                self._emit(
                    "ORDER_REJECTED_INSUFFICIENT_MARGIN",
                    {"owner_id": self.owner_id, "pair": PAIR, "side": side, "units": units},
                    cursor_position=ACTION_POSITION,
                )
                return
            entry = _round_price(
                quote.ask + self.slippage_pips * 0.01
                if side == "LONG"
                else quote.bid - self.slippage_pips * 0.01
            )
            if entry <= 0:
                raise DojoWorkerEconomicReplayError(
                    "slippage produced a non-positive entry price"
                )
            trade_id = self._next_id("T")
            tp, sl = _entry_exits(
                side, entry, parameters["tp_pips"], parameters["sl_pips"]
            )
            self.positions[trade_id] = _Position(
                trade_id=trade_id,
                owner_id=self.owner_id,
                pair=PAIR,
                side=side,
                units=units,
                entry_price=entry,
                opened_ts=quote.ts,
                tp_price=tp,
                sl_price=sl,
            )
            self.entries += 1
            self._emit(
                "FILL_MARKET",
                {
                    "trade_id": trade_id,
                    "owner_id": self.owner_id,
                    "pair": PAIR,
                    "side": side,
                    "units": units,
                    "entry": entry,
                    "tp": tp,
                    "sl": sl,
                    "quote": _quote_payload(quote),
                    "slippage_pips": self.slippage_pips,
                    "action_sequence": action["sequence"],
                },
                cursor_position=ACTION_POSITION,
            )
            self._enforce_margin(quote)
            return
        if name in {"LIMIT", "STOP"}:
            order_id = self._next_id("O")
            self.orders[order_id] = _Order(
                order_id=order_id,
                owner_id=self.owner_id,
                pair=PAIR,
                side=parameters["side"],
                units=parameters["units"],
                trigger_price=parameters["price"],
                tp_pips=parameters["tp_pips"],
                sl_pips=parameters["sl_pips"],
                kind=name,
            )
            self._emit(
                f"ORDER_{name}",
                {
                    "order_id": order_id,
                    "owner_id": self.owner_id,
                    **parameters,
                    "action_sequence": action["sequence"],
                },
                cursor_position=ACTION_POSITION,
            )
            return
        if name == "CANCEL":
            order_id = parameters["order_id"]
            order = self.orders.get(order_id)
            if order is None or order.owner_id != self.owner_id:
                raise DojoWorkerEconomicReplayError(f"unknown owned order: {order_id}")
            del self.orders[order_id]
            self._emit(
                "ORDER_CANCEL",
                {"order_id": order_id, "owner_id": self.owner_id, "action_sequence": action["sequence"]},
                cursor_position=ACTION_POSITION,
            )
            return
        trade_id = parameters["trade_id"]
        position = self.positions.get(trade_id)
        if position is None or position.owner_id != self.owner_id:
            raise DojoWorkerEconomicReplayError(f"unknown owned trade: {trade_id}")
        if name == "CLOSE":
            requested = parameters["units"]
            units = position.units if requested is None else min(requested, position.units)
            price = self._adverse_exit_price(
                position.side, quote.bid if position.side == "LONG" else quote.ask
            )
            self._realize(
                position,
                units=units,
                price=price,
                quote=quote,
                event="CLOSE",
                cursor_position=ACTION_POSITION,
                extra={"action_sequence": action["sequence"]},
            )
            return
        position.tp_price = parameters["tp_price"]
        position.sl_price = parameters["sl_price"]
        self._emit(
            "SET_EXIT",
            {
                "trade_id": trade_id,
                "owner_id": self.owner_id,
                "tp": position.tp_price,
                "sl": position.sl_price,
                "action_sequence": action["sequence"],
            },
            cursor_position=ACTION_POSITION,
        )

    def _adverse_exit_price(self, side: str, observed: float) -> float:
        price = _round_price(
            observed - self.slippage_pips * 0.01
            if side == "LONG"
            else observed + self.slippage_pips * 0.01
        )
        if price <= 0:
            raise DojoWorkerEconomicReplayError(
                "slippage produced a non-positive exit price"
            )
        return price

    def _financing(self, position: _Position, exit_ts: str) -> float:
        if self.financing_pips_per_day <= 0:
            return 0.0
        opened = _phase_epoch(position.opened_ts)
        closed = _phase_epoch(exit_ts)
        if closed < opened:
            raise DojoWorkerEconomicReplayError(
                "financing timestamp precedes position open"
            )
        days = (closed - opened) / 86400.0
        return self.financing_pips_per_day * 0.01 * position.units * days

    def _realize(
        self,
        position: _Position,
        *,
        units: float,
        price: float,
        quote: _Quote,
        event: str,
        cursor_position: str,
        extra: Mapping[str, Any] | None = None,
    ) -> None:
        original_units = position.units
        difference = (
            price - position.entry_price
            if position.side == "LONG"
            else position.entry_price - price
        )
        gross = difference * units
        financing = self._financing(position, quote.ts) * (units / original_units)
        net = gross - financing
        self.balance_jpy += net
        if units >= original_units:
            del self.positions[position.trade_id]
        else:
            position.units -= units
        self.resolved_exits += 1
        self.wins += int(net > 0)
        self.gross_pl_jpy += gross
        self.financing_jpy += financing
        payload = {
            "trade_id": position.trade_id,
            "owner_id": position.owner_id,
            "units": units,
            "price": price,
            "pl_jpy": round(net, 2),
            "gross_pl_jpy": round(gross, 2),
            "financing_jpy": round(financing, 2),
            "quote": _quote_payload(quote),
            "slippage_pips": self.slippage_pips,
        }
        if extra:
            payload.update(extra)
        self._emit(event, payload, cursor_position=cursor_position)

    def _enforce_margin(self, quote: _Quote) -> None:
        if not self.positions or self.account(quote)["margin_usage"] < CLOSEOUT_USAGE:
            return
        for trade_id in list(self.positions):
            position = self.positions[trade_id]
            price = self._adverse_exit_price(
                position.side, quote.bid if position.side == "LONG" else quote.ask
            )
            self.margin_closeouts += 1
            self._realize(
                position,
                units=position.units,
                price=price,
                quote=quote,
                event="MARGIN_CLOSEOUT",
                cursor_position="PHASE_OUTCOMES",
            )

    def settle_period_end(self, quote: _Quote) -> dict[str, Any]:
        requested_orders = list(self.orders)
        requested_trades = list(self.positions)
        for order_id in requested_orders:
            order = self.orders.pop(order_id)
            self._emit(
                "PERIOD_END_CANCEL",
                {"order_id": order_id, "owner_id": order.owner_id},
                cursor_position="PERIOD_END",
            )
        for trade_id in requested_trades:
            position = self.positions[trade_id]
            price = self._adverse_exit_price(
                position.side, quote.bid if position.side == "LONG" else quote.ask
            )
            self._realize(
                position,
                units=position.units,
                price=price,
                quote=quote,
                event="PERIOD_END_CLOSE",
                cursor_position="PERIOD_END",
            )
        receipt = {
            "owner_id": self.owner_id,
            "requested_order_ids": requested_orders,
            "requested_trade_ids": requested_trades,
            "remaining_order_ids": list(self.orders),
            "remaining_trade_ids": list(self.positions),
            "errors": [],
            "complete": not self.orders and not self.positions,
        }
        self._emit("PERIOD_END_SETTLEMENT", receipt, cursor_position="PERIOD_END")
        return receipt


def _validate_action_chain(
    actions: Sequence[Mapping[str, Any]],
    *,
    candidate_id: str,
    owner_id: str,
    intrabar: str,
    quote_cursors: set[tuple[int, str]],
) -> list[dict[str, Any]]:
    if isinstance(actions, (str, bytes)) or not isinstance(actions, Sequence):
        raise DojoWorkerEconomicReplayError("actions must be a sequence")
    phase_order = {phase: index for index, (phase, _) in enumerate(_PHASE_KEYS[intrabar])}
    previous = _ZERO_SHA
    previous_cursor: tuple[int, int] | None = None
    normalized: list[dict[str, Any]] = []
    for index, raw in enumerate(actions, start=1):
        item = dict(_mapping(raw, f"action[{index}]"))
        if set(item) != _INTENT_KEYS:
            raise DojoWorkerEconomicReplayError("action intent schema is not exact")
        supplied_sha = item.pop("action_sha256")
        if (
            item["contract"] != ACTION_INTENT_CONTRACT
            or isinstance(item["schema_version"], bool)
            or not isinstance(item["schema_version"], int)
            or item["schema_version"] != 1
            or item["candidate_id"] != candidate_id
            or item["owner_id"] != owner_id
            or isinstance(item["sequence"], bool)
            or not isinstance(item["sequence"], int)
            or item["sequence"] != index
            or item["previous_action_sha256"] != previous
            or not isinstance(supplied_sha, str)
            or _HEX64.fullmatch(supplied_sha) is None
            or canonical_sha256(item) != supplied_sha
        ):
            raise DojoWorkerEconomicReplayError("action intent chain verification failed")
        cursor = _mapping(item["cursor"], f"action[{index}].cursor")
        if set(cursor) != {"epoch", "phase", "position"}:
            raise DojoWorkerEconomicReplayError("action cursor schema is not exact")
        epoch = cursor["epoch"]
        phase = cursor["phase"]
        if (
            isinstance(epoch, bool)
            or not isinstance(epoch, int)
            or phase not in phase_order
            or cursor["position"] != ACTION_POSITION
            or (epoch, phase) not in quote_cursors
        ):
            raise DojoWorkerEconomicReplayError("action cursor is not in sealed replay")
        cursor_key = (epoch, phase_order[phase])
        if previous_cursor is not None and cursor_key < previous_cursor:
            raise DojoWorkerEconomicReplayError("action cursors are not monotonic")
        previous_cursor = cursor_key
        action_name = item["action"]
        if action_name not in _ACTION_PARAMETER_KEYS:
            raise DojoWorkerEconomicReplayError("unknown action intent")
        parameters = dict(_mapping(item["parameters"], f"action[{index}].parameters"))
        if set(parameters) != _ACTION_PARAMETER_KEYS[action_name]:
            raise DojoWorkerEconomicReplayError("action parameter schema is not exact")
        _validate_action_parameters(action_name, parameters)
        normalized.append({**item, "cursor": dict(cursor), "parameters": parameters, "action_sha256": supplied_sha})
        previous = supplied_sha
    return normalized


def _validate_action_parameters(name: str, parameters: dict[str, Any]) -> None:
    if name in {"MARKET", "LIMIT", "STOP"}:
        if parameters["pair"] != PAIR:
            raise DojoWorkerEconomicReplayError("economic replay supports only USD_JPY")
        if parameters["side"] not in {"LONG", "SHORT"}:
            raise DojoWorkerEconomicReplayError("action side is invalid")
        parameters["units"] = _finite("units", parameters["units"], positive=True)
        for key in ("tp_pips", "sl_pips"):
            if parameters[key] is not None:
                parameters[key] = _finite(key, parameters[key], positive=True)
        if name in {"LIMIT", "STOP"}:
            parameters["price"] = _finite("price", parameters["price"], positive=True)
        return
    if name == "CANCEL":
        _validate_object_id("order_id", parameters["order_id"], "O")
        return
    _validate_object_id("trade_id", parameters["trade_id"], "T")
    if name == "CLOSE":
        if parameters["units"] is not None:
            parameters["units"] = _finite(
                "close units", parameters["units"], positive=True
            )
        return
    for key in ("tp_price", "sl_price"):
        if parameters[key] is not None:
            parameters[key] = _finite(key, parameters[key], positive=True)


def _load_quote_phases(
    corpus_root: Path,
    expected_corpus: Mapping[str, Any],
    *,
    start: datetime,
    end: datetime,
    intrabar: str,
) -> list[_Quote]:
    root = _verify_exact_corpus(corpus_root, expected_corpus)
    rows: dict[int, dict[str, Any]] = {}
    previous_epoch: int | None = None
    for shard in expected_corpus["shards"]:
        path = root / shard["path"]
        try:
            handle = gzip.open(path, "rt", encoding="utf-8")
            with handle:
                for line_number, line in enumerate(handle, start=1):
                    if not line.strip():
                        raise DojoWorkerEconomicReplayError(
                            f"blank corpus row at {shard['path']}:{line_number}"
                        )
                    try:
                        raw = json.loads(
                            line,
                            object_pairs_hook=_object_without_duplicate_keys,
                            parse_constant=_reject_json_constant,
                        )
                    except (json.JSONDecodeError, DojoWorkerEconomicReplayError) as exc:
                        raise DojoWorkerEconomicReplayError(
                            f"invalid corpus JSON at {shard['path']}:{line_number}"
                        ) from exc
                    row, stamp = _validate_corpus_row(raw)
                    if stamp < start or stamp >= end:
                        continue
                    epoch = int(stamp.timestamp())
                    if epoch in rows:
                        raise DojoWorkerEconomicReplayError("duplicate corpus timestamp")
                    if previous_epoch is not None and epoch <= previous_epoch:
                        raise DojoWorkerEconomicReplayError(
                            "eligible corpus rows are not strictly chronological"
                        )
                    rows[epoch] = row
                    previous_epoch = epoch
        except (OSError, EOFError) as exc:
            raise DojoWorkerEconomicReplayError(
                f"cannot decode sealed corpus shard: {shard['path']}"
            ) from exc
    if not rows:
        raise DojoWorkerEconomicReplayError("sealed corpus has no eligible rows")
    phases: list[_Quote] = []
    for epoch, row in rows.items():
        for phase, key in _PHASE_KEYS[intrabar]:
            phases.append(
                _Quote(
                    epoch=epoch,
                    phase=phase,
                    bid=float(row["bid"][key]),
                    ask=float(row["ask"][key]),
                    ts=datetime.fromtimestamp(epoch, tz=timezone.utc).isoformat()
                    + f"#{phase}",
                )
            )
    return phases


def _verify_exact_corpus(
    corpus_root: Path, expected_corpus: Mapping[str, Any]
) -> Path:
    if corpus_root.is_symlink() or not corpus_root.is_dir():
        raise DojoWorkerEconomicReplayError("corpus root must be a real directory")
    root = corpus_root.resolve()
    manifest = _mapping(expected_corpus, "expected_corpus")
    if set(manifest) != {"root", "shards", "corpus_sha256"}:
        raise DojoWorkerEconomicReplayError("expected corpus schema is not exact")
    shards = manifest["shards"]
    if manifest["root"] != str(root) or not isinstance(shards, list) or not shards:
        raise DojoWorkerEconomicReplayError("expected corpus identity is invalid")
    body = {"root": str(root), "shards": shards}
    if manifest["corpus_sha256"] != canonical_sha256(body):
        raise DojoWorkerEconomicReplayError("expected corpus digest drifted")
    expected: dict[str, Mapping[str, Any]] = {}
    for raw in shards:
        item = _mapping(raw, "expected shard")
        if set(item) != {"path", "size_bytes", "sha256"}:
            raise DojoWorkerEconomicReplayError("expected shard schema is not exact")
        relative = item["path"]
        size = item["size_bytes"]
        digest = item["sha256"]
        if not isinstance(relative, str):
            raise DojoWorkerEconomicReplayError("expected shard path must be text")
        rel = Path(relative)
        if rel.is_absolute() or not rel.parts or ".." in rel.parts or rel.as_posix() != relative:
            raise DojoWorkerEconomicReplayError("expected shard path is unsafe")
        if relative in expected:
            raise DojoWorkerEconomicReplayError("expected shard path is duplicated")
        if isinstance(size, bool) or not isinstance(size, int) or size <= 0:
            raise DojoWorkerEconomicReplayError("expected shard size is invalid")
        if not isinstance(digest, str) or _HEX64.fullmatch(digest) is None:
            raise DojoWorkerEconomicReplayError("expected shard digest is invalid")
        expected[relative] = item
    if list(expected) != sorted(expected):
        raise DojoWorkerEconomicReplayError(
            "expected corpus shards are not in canonical path order"
        )
    actual: dict[str, Path] = {}
    for candidate in root.rglob("*"):
        if candidate.is_symlink():
            raise DojoWorkerEconomicReplayError("corpus contains a symlink")
        if candidate.is_dir():
            continue
        if not candidate.is_file():
            raise DojoWorkerEconomicReplayError("corpus contains a non-file entry")
        actual[candidate.relative_to(root).as_posix()] = candidate
    if set(actual) != set(expected):
        raise DojoWorkerEconomicReplayError(
            "corpus file set differs from sealed receipts"
        )
    for relative, path in actual.items():
        seal = expected[relative]
        if path.stat().st_size != seal["size_bytes"] or _file_sha256(path) != seal["sha256"]:
            raise DojoWorkerEconomicReplayError(
                "corpus bytes differ from sealed receipts"
            )
    return root


def _validate_corpus_row(value: Any) -> tuple[dict[str, Any], datetime]:
    row = dict(_mapping(value, "corpus row"))
    if set(row) != {
        "ask",
        "bid",
        "complete",
        "granularity",
        "pair",
        "price",
        "time",
        "volume",
    }:
        raise DojoWorkerEconomicReplayError("corpus row schema is not exact")
    if (
        row["complete"] is not True
        or row["granularity"] != GRANULARITY
        or row["pair"] != PAIR
        or row["price"] != PRICE_COMPONENT
        or isinstance(row["volume"], bool)
        or not isinstance(row["volume"], int)
        or row["volume"] < 0
    ):
        raise DojoWorkerEconomicReplayError("corpus row identity is invalid")
    stamp = _parse_corpus_time(row["time"])
    bid = _validate_ohlc(row["bid"], "bid")
    ask = _validate_ohlc(row["ask"], "ask")
    for key in ("o", "h", "l", "c"):
        if Decimal(ask[key]) < Decimal(bid[key]):
            raise DojoWorkerEconomicReplayError("corpus ask is below bid")
    row["bid"] = bid
    row["ask"] = ask
    return row, stamp


def _validate_ohlc(value: Any, label: str) -> dict[str, str]:
    source = _mapping(value, label)
    if set(source) != {"o", "h", "l", "c"}:
        raise DojoWorkerEconomicReplayError(f"{label} OHLC schema is not exact")
    result: dict[str, str] = {}
    numbers: dict[str, Decimal] = {}
    for key in ("o", "h", "l", "c"):
        raw = source[key]
        if not isinstance(raw, str) or _DECIMAL.fullmatch(raw) is None:
            raise DojoWorkerEconomicReplayError(f"{label}.{key} is not a decimal string")
        try:
            number = Decimal(raw)
        except InvalidOperation as exc:
            raise DojoWorkerEconomicReplayError(f"{label}.{key} is invalid") from exc
        if not number.is_finite() or number <= 0:
            raise DojoWorkerEconomicReplayError(f"{label}.{key} is not positive")
        result[key] = raw
        numbers[key] = number
    if numbers["h"] < max(numbers["o"], numbers["l"], numbers["c"]):
        raise DojoWorkerEconomicReplayError(f"{label} high geometry is invalid")
    if numbers["l"] > min(numbers["o"], numbers["h"], numbers["c"]):
        raise DojoWorkerEconomicReplayError(f"{label} low geometry is invalid")
    return result


def _entry_exits(
    side: str,
    entry: float,
    tp_pips: float | None,
    sl_pips: float | None,
) -> tuple[float | None, float | None]:
    tp = (
        _round_price(entry + tp_pips * 0.01 if side == "LONG" else entry - tp_pips * 0.01)
        if tp_pips
        else None
    )
    sl = (
        _round_price(entry - sl_pips * 0.01 if side == "LONG" else entry + sl_pips * 0.01)
        if sl_pips
        else None
    )
    return tp, sl


def _round_price(value: float) -> float:
    return round(value, 3)


def _quote_payload(quote: _Quote) -> dict[str, Any]:
    return {"bid": quote.bid, "ask": quote.ask, "ts": quote.ts}


def _parse_corpus_time(value: Any) -> datetime:
    if not isinstance(value, str):
        raise DojoWorkerEconomicReplayError("corpus timestamp must be text")
    match = _TIME.fullmatch(value)
    if match is None:
        raise DojoWorkerEconomicReplayError("corpus timestamp is not exact UTC M1")
    try:
        parsed = datetime.fromisoformat(match.group(1) + "+00:00")
    except ValueError as exc:
        raise DojoWorkerEconomicReplayError("corpus timestamp is invalid") from exc
    if parsed.second != 0 or parsed.microsecond != 0:
        raise DojoWorkerEconomicReplayError("corpus timestamp is not M1-aligned")
    return parsed


def _parse_window_time(value: Any, label: str) -> datetime:
    if not isinstance(value, str) or not value:
        raise DojoWorkerEconomicReplayError(f"{label} must be UTC text")
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise DojoWorkerEconomicReplayError(f"{label} is invalid") from exc
    if parsed.tzinfo is None or parsed.utcoffset() != timezone.utc.utcoffset(parsed):
        raise DojoWorkerEconomicReplayError(f"{label} must be UTC")
    return parsed.astimezone(timezone.utc)


def _phase_epoch(value: str) -> float:
    try:
        return datetime.fromisoformat(value.split("#", 1)[0]).timestamp()
    except (TypeError, ValueError) as exc:
        raise DojoWorkerEconomicReplayError("phase timestamp is invalid") from exc


def _mapping(value: Any, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise DojoWorkerEconomicReplayError(f"{label} must be an object")
    return value


def _finite(
    label: str,
    value: Any,
    *,
    positive: bool = False,
    non_negative: bool = False,
) -> float:
    if isinstance(value, bool):
        raise DojoWorkerEconomicReplayError(f"{label} must be a finite number")
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise DojoWorkerEconomicReplayError(f"{label} must be a finite number") from exc
    if not math.isfinite(number):
        raise DojoWorkerEconomicReplayError(f"{label} must be finite")
    if positive and number <= 0:
        raise DojoWorkerEconomicReplayError(f"{label} must be positive")
    if non_negative and number < 0:
        raise DojoWorkerEconomicReplayError(f"{label} must be non-negative")
    return number


def _validate_identifier(label: str, value: Any) -> None:
    if not isinstance(value, str) or _IDENTIFIER.fullmatch(value) is None:
        raise DojoWorkerEconomicReplayError(f"{label} is invalid")


def _validate_object_id(label: str, value: Any, prefix: str) -> None:
    if not isinstance(value, str) or re.fullmatch(prefix + r"[0-9]{6}", value) is None:
        raise DojoWorkerEconomicReplayError(f"{label} is invalid")


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _canonical_json_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise DojoWorkerEconomicReplayError("value is not canonical JSON") from exc


def _reject_json_constant(value: str) -> None:
    raise DojoWorkerEconomicReplayError(
        f"non-finite JSON constant is forbidden: {value}"
    )


def _object_without_duplicate_keys(
    pairs: list[tuple[str, Any]],
) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            raise DojoWorkerEconomicReplayError(
                f"duplicate corpus JSON key is forbidden: {key}"
            )
        value[key] = item
    return value


__all__ = [
    "ACTION_INTENT_CONTRACT",
    "ACTION_POSITION",
    "DojoWorkerEconomicReplayError",
    "ECONOMIC_REPLAY_CONTRACT",
    "canonical_sha256",
    "replay_worker_economics",
    "seal_action_intents",
]
