"""Fail-closed writer primitives for a future DOJO AI inventory room.

This module does not consume a decision and cannot mutate either a virtual or
real broker.  It only seals one point-in-time, AI-authored, paper-virtual
inventory action and appends it to a strict hash-chained JSONL ledger.  The
separately reviewed virtual-broker consumer may consume a row only after
:func:`validate_virtual_action_binding` proves that the exact decision was
durably recorded before the proposed virtual action.

The contract is intentionally narrow:

* decisions are paper-only and keep ``order_authority=NONE``;
* virtual-broker mutation is explicit while every external broker mutation is
  forbidden;
* the AI request, response, producer, model, and immutable evidence packet are
  content-addressed and fresh at the cutoff;
* every dynamic input is at or before one immutable cutoff;
* the record clock is generated by the writer, never supplied in the proposal;
* a repeated evidence identity is idempotent, while a contradictory decision
  for that identity fails closed;
* a new decision is rejected while the deterministic FX weekly market is
  closed; and
* malformed, truncated, reordered, duplicated, or edited ledger rows prevent
  every later append.

``BLOCK_NEW`` blocks only a new virtual entry.  It does not cancel resting
virtual orders; pending-order cancellation needs a separate future contract.
``ALLOW_NEW_VIRTUAL`` creates only a short-lived, single-use permit receipt
for a later entry proxy.  This writer never submits the entry itself.

There is deliberately no import of the virtual broker, live gateway, OANDA
client, paper-room runner, or active/fixed room code.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import math
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

from quant_rabbit.analysis.market_status import compute_market_status
from quant_rabbit.dojo_ai_evidence_packet import (
    entry_signal_identity_sha256,
)


DOJO_AI_INVENTORY_DECISION_CONTRACT = "QR_DOJO_AI_INVENTORY_DECISION_V2"
DOJO_AI_INVENTORY_CONSUMER_CONTRACT = "QR_DOJO_AI_INVENTORY_CONSUMER_V1"
DOJO_AI_INVENTORY_DECISION_ROLE = "PAPER_VIRTUAL_INVENTORY_ACTION"
ALLOWED_VIRTUAL_ACTIONS = frozenset(
    {
        "HOLD",
        "BLOCK_NEW",
        "ALLOW_NEW_VIRTUAL",
        "REDUCE_VIRTUAL",
        "CLOSE_VIRTUAL",
    }
)
GENESIS_DECISION_SHA256 = "0" * 64

# An active paper-room state is expected inside the existing 180-second
# freshness boundary.  Five minutes is a conservative outer integrity ceiling
# for packet assembly and local persistence, not a market or strategy tuning
# parameter.  A wider allowance requires a versioned decision contract.
MAX_DYNAMIC_EVIDENCE_AGE_SECONDS = 300
MAX_RECORD_LAG_SECONDS = 300

# Inventory opinions are review-time evidence, not standing instructions.  One
# hour matches the longest scheduled shadow-review cadence; any longer-lived
# gate needs a new policy/version and fresh evidence.
MAX_DECISION_VALIDITY_SECONDS = 60 * 60
MAX_ENTRY_GATE_VALIDITY_SECONDS = 90

# The narrative input contract treats older-than-24-hour material as stale.
# Per-source ages are caller-declared and policy-bound, but v1 never permits a
# source TTL beyond that existing outer boundary.
MAX_SOURCE_AGE_SECONDS = 24 * 60 * 60

# These are serialization abuse bounds, not market parameters.  A versioned
# schema should replace them if the evidence packet ever needs to grow.
MAX_REASON_CHARS = 1_000
MAX_SOURCE_WATERMARKS = 64
MAX_LEDGER_LINE_BYTES = 256 * 1024
MAX_LEDGER_ROWS = 1_000_000
MAX_POSITION_UNITS = (1 << 63) - 1

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:+/-]{0,255}$")
_REASON_CODE_RE = re.compile(r"^[A-Z][A-Z0-9_]{0,95}$")
_PAIR_RE = re.compile(r"^[A-Z]{3}_[A-Z]{3}$")
_UTC_RE = re.compile(
    r"^(?P<seconds>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})"
    r"(?:\.(?P<fraction>\d{1,9}))?Z$"
)

_PROPOSAL_KEYS = frozenset(
    {
        "contract",
        "cutoff_at_utc",
        "expires_at_utc",
        "action",
        "virtual_units",
        "confidence",
        "admission_binding",
        "reason_code",
        "reason",
        "session_binding",
        "policy_binding",
        "candidate_binding",
        "spec_binding",
        "lifecycle_binding",
        "ai_decision_binding",
        "ledger_binding",
        "state_binding",
        "snapshot_binding",
        "position_binding",
        "quote_binding",
        "source_watermarks",
        "max_dynamic_evidence_age_seconds",
        "max_record_lag_seconds",
        "paper_only",
        "order_authority",
        "live_permission",
        "virtual_broker_mutation_allowed",
        "external_broker_mutation_allowed",
        "consumer_contract",
        "decision_role",
        "decision_identity_sha256",
    }
)
_RECORD_CHAIN_KEYS = frozenset(
    {
        "sequence",
        "previous_decision_sha256",
        "recorded_at_utc",
        "record_lag_nanoseconds",
        "decision_sha256",
    }
)
_RECORD_KEYS = _PROPOSAL_KEYS | _RECORD_CHAIN_KEYS
_SESSION_BINDING_KEYS = frozenset(
    {
        "experiment_id",
        "room_id",
        "session_contract_sha256",
        "observed_at_utc",
    }
)
_POLICY_BINDING_KEYS = frozenset({"policy_id", "policy_sha256", "observed_at_utc"})
_CANDIDATE_BINDING_KEYS = frozenset(
    {"candidate_id", "candidate_sha256", "observed_at_utc"}
)
_SPEC_BINDING_KEYS = frozenset({"spec_id", "spec_sha256", "observed_at_utc"})
_LIFECYCLE_BINDING_KEYS = frozenset(
    {
        "paper_eligible_event_sha256",
        "candidate_lifecycle_ledger_tip_sha256",
        "observed_at_utc",
    }
)
_AI_DECISION_BINDING_KEYS = frozenset(
    {
        "producer_id",
        "model_id",
        "request_sha256",
        "response_sha256",
        "evidence_packet_sha256",
        "producer_receipt_sha256",
        "produced_at_utc",
        "observed_at_utc",
    }
)
_DIGEST_BINDING_KEYS = frozenset({"sha256", "observed_at_utc"})
_POSITION_BINDING_KEYS = frozenset(
    {
        "position_id",
        "pair",
        "side",
        "units",
        "strategy_tag",
        "entry_context_sha256",
        "sha256",
        "observed_at_utc",
    }
)
_QUOTE_BINDING_KEYS = frozenset({"pair", "bid", "ask", "sha256", "observed_at_utc"})
_SOURCE_WATERMARK_KEYS = frozenset(
    {"source_id", "sha256", "watermark_at_utc", "max_age_seconds"}
)
_ADMISSION_BINDING_KEYS = frozenset(
    {"entry_signal", "evidence_packet_sha256", "permit_expires_at_utc"}
)
_ENTRY_SIGNAL_KEYS = frozenset(
    {
        "signal_identity_sha256",
        "pair",
        "side",
        "order_type",
        "units",
        "price",
        "strategy_tag",
        "entry_context_sha256",
        "tp_pips",
        "sl_pips",
        "observed_at_utc",
    }
)

# One evidence identity admits exactly one semantic decision.  Action and prose
# are intentionally excluded so a retry that changes either conflicts instead
# of silently minting a second identity from the same observation.
_IDENTITY_KEYS = (
    "contract",
    "cutoff_at_utc",
    "expires_at_utc",
    "session_binding",
    "policy_binding",
    "candidate_binding",
    "spec_binding",
    "lifecycle_binding",
    "ai_decision_binding",
    "ledger_binding",
    "state_binding",
    "snapshot_binding",
    "position_binding",
    "quote_binding",
    "admission_binding",
    "source_watermarks",
    "max_dynamic_evidence_age_seconds",
    "max_record_lag_seconds",
)


class InventoryDecisionError(RuntimeError):
    """Base class for fail-closed decision-writer failures."""


class InventoryLedgerIntegrityError(InventoryDecisionError):
    """The existing append-only ledger cannot be trusted."""


class InventoryDecisionConflictError(InventoryDecisionError):
    """The same evidence identity already has a different decision."""


class InventoryMarketClosedError(InventoryDecisionError):
    """A new decision was attempted outside the open FX week."""


@dataclass(frozen=True)
class InventoryAppendResult:
    """Result of one append attempt."""

    record: dict[str, Any]
    appended: bool


def seal_inventory_decision_proposal(value: Mapping[str, Any]) -> dict[str, Any]:
    """Canonicalize and seal one immutable-cutoff decision proposal.

    The cutoff itself must be inside the deterministic DST-aware FX week.  The
    append writer independently checks its own record clock as well.
    """

    if not isinstance(value, Mapping):
        raise TypeError("inventory decision proposal must be a mapping")
    proposal = _snapshot_mapping(value, "inventory decision proposal")
    proposal.pop("decision_identity_sha256", None)

    for binding_name in (
        "session_binding",
        "policy_binding",
        "candidate_binding",
        "spec_binding",
        "lifecycle_binding",
        "ai_decision_binding",
        "ledger_binding",
        "state_binding",
        "snapshot_binding",
        "position_binding",
        "quote_binding",
    ):
        binding = proposal.get(binding_name)
        if isinstance(binding, Mapping):
            proposal[binding_name] = _snapshot_mapping(binding, binding_name)
    admission = proposal.get("admission_binding")
    if isinstance(admission, Mapping):
        normalized_admission = _snapshot_mapping(admission, "admission_binding")
        entry_signal = normalized_admission.get("entry_signal")
        if isinstance(entry_signal, Mapping):
            normalized_admission["entry_signal"] = _snapshot_mapping(
                entry_signal, "admission_binding.entry_signal"
            )
        proposal["admission_binding"] = normalized_admission
    sources = proposal.get("source_watermarks")
    if isinstance(sources, Sequence) and not isinstance(sources, (str, bytes)):
        proposal["source_watermarks"] = [
            _snapshot_mapping(item, "source watermark")
            if isinstance(item, Mapping)
            else item
            for item in sources
        ]

    quote = proposal.get("quote_binding")
    if isinstance(quote, dict):
        for key in ("bid", "ask"):
            parsed = _finite_number(quote.get(key))
            if parsed is not None:
                quote[key] = 0.0 if parsed == 0.0 else parsed
    position = proposal.get("position_binding")
    if isinstance(position, dict):
        parsed_units = _finite_number(position.get("units"))
        if parsed_units is not None:
            position["units"] = 0.0 if parsed_units == 0.0 else parsed_units
    parsed_virtual_units = _finite_number(proposal.get("virtual_units"))
    if parsed_virtual_units is not None:
        proposal["virtual_units"] = (
            0.0 if parsed_virtual_units == 0.0 else parsed_virtual_units
        )

    for timestamp_path in _proposal_timestamp_paths(proposal):
        container, key = timestamp_path
        parsed = _parse_utc_nanoseconds(container.get(key))
        if parsed is not None:
            container[key] = _canonical_utc(parsed)

    provisional = dict(proposal)
    provisional["decision_identity_sha256"] = GENESIS_DECISION_SHA256
    issues = _proposal_issues(provisional, verify_identity=False)
    if issues:
        raise ValueError("invalid inventory decision proposal: " + "; ".join(issues))

    cutoff = _datetime_from_canonical(provisional["cutoff_at_utc"])
    try:
        is_open = compute_market_status(cutoff).is_fx_open
    except Exception as exc:
        raise InventoryDecisionError(
            "FX market status is unavailable; decision creation failed closed"
        ) from exc
    if not is_open:
        raise InventoryMarketClosedError(
            "new DOJO AI inventory decisions are disabled while FX is closed"
        )

    provisional["decision_identity_sha256"] = inventory_decision_identity_sha256(
        provisional
    )
    final_issues = _proposal_issues(provisional, verify_identity=True)
    if final_issues:
        raise ValueError(
            "invalid sealed inventory decision proposal: " + "; ".join(final_issues)
        )
    return provisional


def inventory_decision_identity_sha256(value: Mapping[str, Any]) -> str:
    """Return the canonical evidence identity for a proposal or record."""

    snapshot = _snapshot_mapping(value, "inventory decision")
    body = {key: snapshot.get(key) for key in _IDENTITY_KEYS}
    return _canonical_sha256(body)


def inventory_decision_sha256(value: Mapping[str, Any]) -> str:
    """Return the canonical record digest, excluding the digest itself."""

    snapshot = _snapshot_mapping(value, "inventory decision record")
    body = {key: item for key, item in snapshot.items() if key != "decision_sha256"}
    return _canonical_sha256(body)


def validate_inventory_decision(value: object) -> tuple[str, ...]:
    """Return exact validation issues for one fully chained decision row."""

    if not isinstance(value, Mapping):
        return ("RECORD_NOT_MAPPING",)
    try:
        record = _snapshot_mapping(value, "inventory decision record")
    except ValueError:
        return ("RECORD_SNAPSHOT_UNREADABLE",)

    issues = _proposal_issues(record, verify_identity=True)
    keys = _exact_string_keys(record)
    for key in sorted(_RECORD_KEYS - keys):
        issues.append(f"MISSING_RECORD_FIELD:{key}")
    for key in sorted(keys - _RECORD_KEYS):
        issues.append(f"UNKNOWN_RECORD_FIELD:{key}")

    sequence = record.get("sequence")
    if not _is_exact_int(sequence) or sequence < 1:
        issues.append("INVALID_SEQUENCE")
    previous = record.get("previous_decision_sha256")
    if not _is_sha256(previous):
        issues.append("INVALID_PREVIOUS_DECISION_SHA256")
    recorded = _parse_utc_nanoseconds(record.get("recorded_at_utc"))
    cutoff = _parse_utc_nanoseconds(record.get("cutoff_at_utc"))
    lag = record.get("record_lag_nanoseconds")
    if recorded is None:
        issues.append("INVALID_RECORDED_AT_UTC")
    elif record.get("recorded_at_utc") != _canonical_utc(recorded):
        issues.append("NON_CANONICAL_RECORDED_AT_UTC")
    if not _is_exact_int(lag) or lag < 0:
        issues.append("INVALID_RECORD_LAG_NANOSECONDS")
    elif recorded is not None and cutoff is not None:
        computed_lag = recorded - cutoff
        if lag != computed_lag:
            issues.append("RECORD_LAG_MISMATCH")
        max_lag = record.get("max_record_lag_seconds")
        if _is_exact_int(max_lag) and computed_lag > max_lag * 1_000_000_000:
            issues.append("RECORD_LAG_EXCEEDED")
    expires = _parse_utc_nanoseconds(record.get("expires_at_utc"))
    if recorded is not None and expires is not None and recorded >= expires:
        issues.append("DECISION_EXPIRED_BEFORE_RECORD")
    ai_decision = record.get("ai_decision_binding")
    if isinstance(ai_decision, Mapping):
        produced = _parse_utc_nanoseconds(ai_decision.get("produced_at_utc"))
        if recorded is not None and produced is not None and recorded < produced:
            issues.append("DECISION_RECORDED_BEFORE_AI_PRODUCTION")

    stored_sha = record.get("decision_sha256")
    if not _is_sha256(stored_sha):
        issues.append("INVALID_DECISION_SHA256")
    else:
        try:
            computed_sha = inventory_decision_sha256(record)
        except (TypeError, ValueError):
            computed_sha = None
        if computed_sha is None or stored_sha != computed_sha:
            issues.append("DECISION_SHA256_MISMATCH")
    return tuple(_dedupe(issues))


def validate_inventory_decision_ledger(path: Path | str) -> dict[str, Any]:
    """Validate a complete ledger snapshot without modifying it."""

    ledger_path = Path(path)
    if not ledger_path.exists():
        return _ledger_validation_result((), rows=(), terminal_sha256=None)
    try:
        with ledger_path.open("rb") as handle:
            fcntl.flock(handle.fileno(), fcntl.LOCK_SH)
            try:
                raw = handle.read()
            finally:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
    except OSError as exc:
        return _ledger_validation_result(
            (f"LEDGER_READ_FAILED:{exc.__class__.__name__}",),
            rows=(),
            terminal_sha256=None,
        )
    rows, issues = _decode_ledger_bytes(raw)
    return _validate_ledger_rows(rows, initial_issues=issues)


def append_inventory_decision(
    path: Path | str,
    proposal: Mapping[str, Any],
) -> InventoryAppendResult:
    """Append one decision under an exclusive lock.

    The record clock comes from :func:`_utc_now`; callers cannot backdate it.
    A crash that leaves a partial line causes the next operation to fail closed
    rather than truncating or repairing history.
    """

    sealed = seal_inventory_decision_proposal(proposal)
    ledger_path = Path(path)
    ledger_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with ledger_path.open("a+b") as handle:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
            try:
                handle.seek(0)
                raw = handle.read()
                rows, decode_issues = _decode_ledger_bytes(raw)
                validation = _validate_ledger_rows(rows, initial_issues=decode_issues)
                if not validation["valid"]:
                    raise InventoryLedgerIntegrityError(
                        "inventory decision ledger failed validation: "
                        + "; ".join(validation["issues"])
                    )

                existing = _find_identity(rows, sealed["decision_identity_sha256"])
                if existing is not None:
                    if _proposal_projection(existing) != sealed:
                        raise InventoryDecisionConflictError(
                            "same evidence identity already has a different decision"
                        )
                    return InventoryAppendResult(record=dict(existing), appended=False)

                now = _utc_now().astimezone(timezone.utc)
                try:
                    is_open = compute_market_status(now).is_fx_open
                except Exception as exc:
                    raise InventoryDecisionError(
                        "FX market status is unavailable; append failed closed"
                    ) from exc
                if not is_open:
                    raise InventoryMarketClosedError(
                        "new DOJO AI inventory decisions are disabled while FX is closed"
                    )

                recorded_at = _datetime_to_canonical(now)
                recorded_ns = _parse_utc_nanoseconds(recorded_at)
                cutoff_ns = _parse_utc_nanoseconds(sealed["cutoff_at_utc"])
                assert recorded_ns is not None and cutoff_ns is not None
                lag_ns = recorded_ns - cutoff_ns
                max_lag_ns = sealed["max_record_lag_seconds"] * 1_000_000_000
                if lag_ns < 0:
                    raise InventoryDecisionError(
                        "writer clock precedes immutable decision cutoff"
                    )
                if lag_ns > max_lag_ns:
                    raise InventoryDecisionError(
                        "decision record lag exceeds the sealed policy limit"
                    )
                expires_ns = _parse_utc_nanoseconds(sealed["expires_at_utc"])
                assert expires_ns is not None
                if recorded_ns >= expires_ns:
                    raise InventoryDecisionError(
                        "decision expired before it could be durably recorded"
                    )

                previous = (
                    rows[-1]["decision_sha256"] if rows else GENESIS_DECISION_SHA256
                )
                record: dict[str, Any] = {
                    **sealed,
                    "sequence": len(rows) + 1,
                    "previous_decision_sha256": previous,
                    "recorded_at_utc": recorded_at,
                    "record_lag_nanoseconds": lag_ns,
                }
                record["decision_sha256"] = inventory_decision_sha256(record)
                record_issues = validate_inventory_decision(record)
                if record_issues:
                    raise InventoryDecisionError(
                        "constructed decision failed validation: "
                        + "; ".join(record_issues)
                    )

                encoded = _canonical_json(record).encode("utf-8") + b"\n"
                if len(encoded) > MAX_LEDGER_LINE_BYTES:
                    raise InventoryDecisionError(
                        "decision record exceeds the bounded ledger line size"
                    )
                handle.seek(0, os.SEEK_END)
                handle.write(encoded)
                handle.flush()
                os.fsync(handle.fileno())
                return InventoryAppendResult(record=record, appended=True)
            finally:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
    except InventoryDecisionError:
        raise
    except OSError as exc:
        raise InventoryDecisionError("inventory decision append failed") from exc


def validate_virtual_action_binding(
    decision: object,
    *,
    decision_sha256: str,
    action: str,
    virtual_units: float | None,
    action_at_utc: str,
) -> tuple[str, ...]:
    """Prove decision-before-action for a future virtual-only consumer.

    Passing this validator is necessary but never sufficient to mutate even a
    paper broker.  The future consumer must additionally revalidate its own
    room, virtual-broker state, and append the resulting virtual event.
    """

    issues = list(validate_inventory_decision(decision))
    if not isinstance(decision, Mapping):
        return tuple(_dedupe([*issues, "DECISION_NOT_MAPPING"]))
    try:
        record = _snapshot_mapping(decision, "inventory decision record")
    except ValueError:
        return tuple(_dedupe([*issues, "DECISION_SNAPSHOT_UNREADABLE"]))

    if not _is_sha256(decision_sha256):
        issues.append("INVALID_BOUND_DECISION_SHA256")
    elif record.get("decision_sha256") != decision_sha256:
        issues.append("BOUND_DECISION_SHA256_MISMATCH")
    if action not in ALLOWED_VIRTUAL_ACTIONS or record.get("action") != action:
        issues.append("ACTION_MISMATCH")
    if virtual_units is not None and (
        virtual_units.__class__ is not float or _finite_number(virtual_units) is None
    ):
        issues.append("NON_CANONICAL_BOUND_VIRTUAL_UNITS")
    if record.get("virtual_units") != virtual_units:
        issues.append("VIRTUAL_UNITS_MISMATCH")

    action_ns = _parse_utc_nanoseconds(action_at_utc)
    recorded_ns = _parse_utc_nanoseconds(record.get("recorded_at_utc"))
    if action_ns is None:
        issues.append("INVALID_ACTION_AT_UTC")
    elif action_at_utc != _canonical_utc(action_ns):
        issues.append("NON_CANONICAL_ACTION_AT_UTC")
    elif recorded_ns is not None and action_ns <= recorded_ns:
        issues.append("ACTION_NOT_AFTER_DURABLE_DECISION")
    expires_ns = _parse_utc_nanoseconds(record.get("expires_at_utc"))
    if action_ns is not None and expires_ns is not None and action_ns >= expires_ns:
        issues.append("ACTION_AFTER_DECISION_EXPIRY")

    if (
        record.get("paper_only") is not True
        or record.get("order_authority") != "NONE"
        or record.get("live_permission") is not False
        or record.get("virtual_broker_mutation_allowed") is not True
        or record.get("external_broker_mutation_allowed") is not False
        or record.get("consumer_contract") != DOJO_AI_INVENTORY_CONSUMER_CONTRACT
        or record.get("decision_role") != DOJO_AI_INVENTORY_DECISION_ROLE
    ):
        issues.append("PAPER_ONLY_SAFETY_INVARIANT_FAILED")
    return tuple(_dedupe(issues))


def _proposal_issues(
    proposal: Mapping[str, Any],
    *,
    verify_identity: bool,
) -> list[str]:
    issues: list[str] = []
    keys = _exact_string_keys(proposal)
    for key in sorted(_PROPOSAL_KEYS - keys):
        issues.append(f"MISSING_PROPOSAL_FIELD:{key}")
    # A record legitimately has the five chain keys in addition to a proposal.
    for key in sorted(keys - _PROPOSAL_KEYS - _RECORD_CHAIN_KEYS):
        issues.append(f"UNKNOWN_PROPOSAL_FIELD:{key}")

    if proposal.get("contract") != DOJO_AI_INVENTORY_DECISION_CONTRACT:
        issues.append("INVALID_CONTRACT")
    required_safety = {
        "paper_only": True,
        "order_authority": "NONE",
        "live_permission": False,
        "virtual_broker_mutation_allowed": True,
        "external_broker_mutation_allowed": False,
        "consumer_contract": DOJO_AI_INVENTORY_CONSUMER_CONTRACT,
        "decision_role": DOJO_AI_INVENTORY_DECISION_ROLE,
    }
    for key, expected in required_safety.items():
        if proposal.get(key) is not expected and proposal.get(key) != expected:
            issues.append(f"SAFETY_INVARIANT_FAILED:{key}")

    cutoff = _parse_utc_nanoseconds(proposal.get("cutoff_at_utc"))
    if cutoff is None:
        issues.append("INVALID_CUTOFF_AT_UTC")
    elif proposal.get("cutoff_at_utc") != _canonical_utc(cutoff):
        issues.append("NON_CANONICAL_CUTOFF_AT_UTC")
    expires = _parse_utc_nanoseconds(proposal.get("expires_at_utc"))
    if expires is None:
        issues.append("INVALID_EXPIRES_AT_UTC")
    elif proposal.get("expires_at_utc") != _canonical_utc(expires):
        issues.append("NON_CANONICAL_EXPIRES_AT_UTC")
    elif cutoff is not None:
        if expires <= cutoff:
            issues.append("EXPIRY_NOT_AFTER_CUTOFF")
        elif expires - cutoff > MAX_DECISION_VALIDITY_SECONDS * 1_000_000_000:
            issues.append("EXPIRY_EXCEEDS_MAXIMUM_VALIDITY")

    max_dynamic_age = proposal.get("max_dynamic_evidence_age_seconds")
    if (
        not _is_exact_int(max_dynamic_age)
        or not 1 <= max_dynamic_age <= MAX_DYNAMIC_EVIDENCE_AGE_SECONDS
    ):
        issues.append("INVALID_MAX_DYNAMIC_EVIDENCE_AGE_SECONDS")
    max_record_lag = proposal.get("max_record_lag_seconds")
    if (
        not _is_exact_int(max_record_lag)
        or not 1 <= max_record_lag <= MAX_RECORD_LAG_SECONDS
    ):
        issues.append("INVALID_MAX_RECORD_LAG_SECONDS")

    for name, expected_keys in (
        ("session_binding", _SESSION_BINDING_KEYS),
        ("policy_binding", _POLICY_BINDING_KEYS),
        ("candidate_binding", _CANDIDATE_BINDING_KEYS),
        ("spec_binding", _SPEC_BINDING_KEYS),
        ("lifecycle_binding", _LIFECYCLE_BINDING_KEYS),
    ):
        binding = proposal.get(name)
        issues.extend(
            _binding_issues(
                name,
                binding,
                expected_keys=expected_keys,
                cutoff=cutoff,
                max_age_seconds=None,
            )
        )
    for name in ("ledger_binding", "state_binding", "snapshot_binding"):
        binding = proposal.get(name)
        issues.extend(
            _binding_issues(
                name,
                binding,
                expected_keys=_DIGEST_BINDING_KEYS,
                cutoff=cutoff,
                max_age_seconds=max_dynamic_age
                if _is_exact_int(max_dynamic_age)
                else None,
            )
        )
    issues.extend(
        _binding_issues(
            "ai_decision_binding",
            proposal.get("ai_decision_binding"),
            expected_keys=_AI_DECISION_BINDING_KEYS,
            cutoff=cutoff,
            max_age_seconds=max_dynamic_age if _is_exact_int(max_dynamic_age) else None,
        )
    )
    ai_decision = proposal.get("ai_decision_binding")
    if isinstance(ai_decision, Mapping):
        produced_at = _parse_utc_nanoseconds(ai_decision.get("produced_at_utc"))
        observed_at = _parse_utc_nanoseconds(ai_decision.get("observed_at_utc"))
        if produced_at is None:
            issues.append("ai_decision_binding:INVALID_PRODUCED_AT_UTC")
        elif ai_decision.get("produced_at_utc") != _canonical_utc(produced_at):
            issues.append("ai_decision_binding:NON_CANONICAL_PRODUCED_AT_UTC")
        elif observed_at is not None:
            if produced_at < observed_at:
                issues.append("AI_DECISION_PRODUCED_BEFORE_EVIDENCE_CUTOFF")
            elif (
                _is_exact_int(max_dynamic_age)
                and produced_at - observed_at > max_dynamic_age * 1_000_000_000
            ):
                issues.append("AI_DECISION_PRODUCTION_LAG_EXCEEDED")
        if cutoff is not None and produced_at is not None and produced_at > cutoff:
            issues.append("AI_DECISION_PRODUCED_AFTER_DECISION_CUTOFF")

    position = proposal.get("position_binding")
    issues.extend(
        _binding_issues(
            "position_binding",
            position,
            expected_keys=_POSITION_BINDING_KEYS,
            cutoff=cutoff,
            max_age_seconds=max_dynamic_age if _is_exact_int(max_dynamic_age) else None,
        )
    )
    position_units: float | None = None
    position_pair: str | None = None
    if isinstance(position, Mapping):
        position_id = position.get("position_id")
        if not _is_identifier(position_id):
            issues.append("INVALID_POSITION_ID")
        if not _is_identifier(position.get("strategy_tag")):
            issues.append("INVALID_POSITION_STRATEGY_TAG")
        if not _is_sha256(position.get("entry_context_sha256")):
            issues.append("INVALID_POSITION_ENTRY_CONTEXT_SHA256")
        position_pair = position.get("pair") if _is_pair(position.get("pair")) else None
        if position_pair is None:
            issues.append("INVALID_POSITION_PAIR")
        side = position.get("side")
        position_units_raw = position.get("units")
        parsed_position_units = _finite_number(position_units_raw)
        if (
            position_units_raw.__class__ is not float
            or parsed_position_units is None
            or not 0.0 <= parsed_position_units <= MAX_POSITION_UNITS
        ):
            issues.append("INVALID_POSITION_UNITS")
        else:
            position_units = parsed_position_units
            if position_units == 0.0 and side != "FLAT":
                issues.append("FLAT_POSITION_SIDE_REQUIRED")
            if position_units > 0.0 and side not in {"LONG", "SHORT"}:
                issues.append("OPEN_POSITION_SIDE_REQUIRED")
            if position_units == 0.0:
                expected_flat_id = (
                    f"FLAT:{position_pair}" if position_pair is not None else None
                )
                if position_id != expected_flat_id:
                    issues.append("INVALID_FLAT_POSITION_ID")

    quote = proposal.get("quote_binding")
    issues.extend(
        _binding_issues(
            "quote_binding",
            quote,
            expected_keys=_QUOTE_BINDING_KEYS,
            cutoff=cutoff,
            max_age_seconds=max_dynamic_age if _is_exact_int(max_dynamic_age) else None,
        )
    )
    if isinstance(quote, Mapping):
        quote_pair = quote.get("pair")
        if not _is_pair(quote_pair):
            issues.append("INVALID_QUOTE_PAIR")
        elif position_pair is not None and quote_pair != position_pair:
            issues.append("POSITION_QUOTE_PAIR_MISMATCH")
        bid = _finite_number(quote.get("bid"))
        ask = _finite_number(quote.get("ask"))
        if bid is None or bid <= 0.0 or quote.get("bid").__class__ is not float:
            issues.append("INVALID_QUOTE_BID")
        if ask is None or ask <= 0.0 or quote.get("ask").__class__ is not float:
            issues.append("INVALID_QUOTE_ASK")
        if bid is not None and ask is not None and ask < bid:
            issues.append("CROSSED_QUOTE")

    action = proposal.get("action")
    if action not in ALLOWED_VIRTUAL_ACTIONS:
        issues.append("INVALID_ACTION")
    confidence = proposal.get("confidence")
    parsed_confidence = _finite_number(confidence)
    if (
        confidence.__class__ is not float
        or parsed_confidence is None
        or not 0.0 <= parsed_confidence <= 1.0
    ):
        issues.append("INVALID_CONFIDENCE")
    admission = proposal.get("admission_binding")
    if action == "ALLOW_NEW_VIRTUAL":
        if not isinstance(admission, Mapping):
            issues.append("ALLOW_NEW_VIRTUAL_REQUIRES_ADMISSION_BINDING")
        else:
            admission_keys = _exact_string_keys(admission)
            for key in sorted(_ADMISSION_BINDING_KEYS - admission_keys):
                issues.append(f"admission_binding:MISSING_FIELD:{key}")
            for key in sorted(admission_keys - _ADMISSION_BINDING_KEYS):
                issues.append(f"admission_binding:UNKNOWN_FIELD:{key}")
            evidence_packet_sha256 = admission.get("evidence_packet_sha256")
            if not _is_sha256(evidence_packet_sha256):
                issues.append("admission_binding:INVALID_EVIDENCE_PACKET_SHA256")
            elif isinstance(
                ai_decision, Mapping
            ) and evidence_packet_sha256 != ai_decision.get("evidence_packet_sha256"):
                issues.append("ADMISSION_EVIDENCE_PACKET_MISMATCH")
            entry_signal = admission.get("entry_signal")
            if not isinstance(entry_signal, Mapping):
                issues.append("admission_binding:ENTRY_SIGNAL_NOT_MAPPING")
            else:
                entry_signal_keys = _exact_string_keys(entry_signal)
                for key in sorted(_ENTRY_SIGNAL_KEYS - entry_signal_keys):
                    issues.append(f"admission_binding.entry_signal:MISSING_FIELD:{key}")
                for key in sorted(entry_signal_keys - _ENTRY_SIGNAL_KEYS):
                    issues.append(f"admission_binding.entry_signal:UNKNOWN_FIELD:{key}")
                signal_identity = entry_signal.get("signal_identity_sha256")
                if not _is_sha256(signal_identity):
                    issues.append(
                        "admission_binding.entry_signal:"
                        "INVALID_SIGNAL_IDENTITY_SHA256"
                    )
                else:
                    try:
                        expected_signal_identity = entry_signal_identity_sha256(
                            entry_signal
                        )
                    except (TypeError, ValueError):
                        expected_signal_identity = None
                    if signal_identity != expected_signal_identity:
                        issues.append("ENTRY_SIGNAL_IDENTITY_MISMATCH")
                signal_pair = entry_signal.get("pair")
                if not _is_pair(signal_pair):
                    issues.append("admission_binding.entry_signal:INVALID_PAIR")
                elif isinstance(position, Mapping) and signal_pair != position.get(
                    "pair"
                ):
                    issues.append("ADMISSION_POSITION_PAIR_MISMATCH")
                signal_strategy = entry_signal.get("strategy_tag")
                if not _is_identifier(signal_strategy):
                    issues.append("admission_binding.entry_signal:INVALID_STRATEGY_TAG")
                elif isinstance(position, Mapping) and signal_strategy != position.get(
                    "strategy_tag"
                ):
                    issues.append("ADMISSION_POSITION_STRATEGY_TAG_MISMATCH")
                signal_entry_context = entry_signal.get("entry_context_sha256")
                if not _is_sha256(signal_entry_context):
                    issues.append(
                        "admission_binding.entry_signal:" "INVALID_ENTRY_CONTEXT_SHA256"
                    )
                elif isinstance(
                    position, Mapping
                ) and signal_entry_context != position.get("entry_context_sha256"):
                    issues.append("ADMISSION_POSITION_ENTRY_CONTEXT_MISMATCH")
                if entry_signal.get("side") not in {"LONG", "SHORT"}:
                    issues.append("admission_binding.entry_signal:INVALID_SIDE")
                order_type = entry_signal.get("order_type")
                if order_type not in {"MARKET", "LIMIT", "STOP"}:
                    issues.append("admission_binding.entry_signal:INVALID_ORDER_TYPE")
                signal_units = entry_signal.get("units")
                parsed_signal_units = _finite_number(signal_units)
                if (
                    signal_units.__class__ is not float
                    or parsed_signal_units is None
                    or parsed_signal_units <= 0.0
                ):
                    issues.append("admission_binding.entry_signal:INVALID_UNITS")
                signal_price = entry_signal.get("price")
                if order_type == "MARKET":
                    if signal_price is not None:
                        issues.append(
                            "admission_binding.entry_signal:"
                            "MARKET_PRICE_MUST_BE_NULL"
                        )
                else:
                    parsed_signal_price = _finite_number(signal_price)
                    if (
                        signal_price is None
                        or signal_price.__class__ is not float
                        or parsed_signal_price is None
                        or parsed_signal_price <= 0.0
                    ):
                        issues.append("admission_binding.entry_signal:INVALID_PRICE")
                for numeric_field in ("tp_pips", "sl_pips"):
                    raw_number = entry_signal.get(numeric_field)
                    parsed_number = _finite_number(raw_number)
                    if raw_number is not None and (
                        raw_number.__class__ is not float
                        or parsed_number is None
                        or parsed_number <= 0.0
                    ):
                        issues.append(
                            "admission_binding.entry_signal:"
                            f"INVALID_{numeric_field.upper()}"
                        )
                signal_observed = _parse_utc_nanoseconds(
                    entry_signal.get("observed_at_utc")
                )
                if signal_observed is None:
                    issues.append(
                        "admission_binding.entry_signal:" "INVALID_OBSERVED_AT_UTC"
                    )
                elif entry_signal.get("observed_at_utc") != _canonical_utc(
                    signal_observed
                ):
                    issues.append(
                        "admission_binding.entry_signal:"
                        "NON_CANONICAL_OBSERVED_AT_UTC"
                    )
                elif cutoff is not None:
                    if signal_observed > cutoff:
                        issues.append(
                            "admission_binding.entry_signal:" "OBSERVED_AFTER_CUTOFF"
                        )
                    elif (
                        _is_exact_int(max_dynamic_age)
                        and cutoff - signal_observed > max_dynamic_age * 1_000_000_000
                    ):
                        issues.append(
                            "admission_binding.entry_signal:" "STALE_AT_CUTOFF"
                        )
            permit_expires = _parse_utc_nanoseconds(
                admission.get("permit_expires_at_utc")
            )
            if permit_expires is None:
                issues.append("admission_binding:INVALID_PERMIT_EXPIRES_AT_UTC")
            elif admission.get("permit_expires_at_utc") != _canonical_utc(
                permit_expires
            ):
                issues.append("admission_binding:NON_CANONICAL_PERMIT_EXPIRES_AT_UTC")
            elif cutoff is not None:
                if permit_expires <= cutoff:
                    issues.append("ADMISSION_PERMIT_NOT_AFTER_CUTOFF")
                elif (
                    permit_expires - cutoff
                    > MAX_ENTRY_GATE_VALIDITY_SECONDS * 1_000_000_000
                ):
                    issues.append("ADMISSION_PERMIT_EXCEEDS_SHORT_TTL")
                if expires is not None and permit_expires > expires:
                    issues.append("ADMISSION_PERMIT_AFTER_DECISION_EXPIRY")
    elif admission is not None:
        issues.append("ADMISSION_BINDING_MUST_BE_NULL")

    virtual_units = proposal.get("virtual_units")
    entry_gate_action = action in {"BLOCK_NEW", "ALLOW_NEW_VIRTUAL"}
    if action in {"HOLD", "BLOCK_NEW", "ALLOW_NEW_VIRTUAL"}:
        if virtual_units is not None:
            issues.append("VIRTUAL_UNITS_MUST_BE_NULL")
        if action == "HOLD" and position_units == 0.0:
            issues.append("HOLD_REQUIRES_OPEN_POSITION")
        if entry_gate_action and position_units != 0.0:
            issues.append("ENTRY_GATE_REQUIRES_FLAT_BINDING")
        if (
            entry_gate_action
            and cutoff is not None
            and expires is not None
            and expires - cutoff > MAX_ENTRY_GATE_VALIDITY_SECONDS * 1_000_000_000
        ):
            issues.append("ENTRY_GATE_EXPIRY_EXCEEDS_SHORT_TTL")
    elif action == "REDUCE_VIRTUAL":
        parsed_virtual_units = _finite_number(virtual_units)
        if (
            virtual_units.__class__ is not float
            or parsed_virtual_units is None
            or position_units is None
            or not 0.0 < parsed_virtual_units < position_units
        ):
            issues.append("INVALID_REDUCE_VIRTUAL_UNITS")
    elif action == "CLOSE_VIRTUAL":
        parsed_virtual_units = _finite_number(virtual_units)
        if (
            virtual_units.__class__ is not float
            or parsed_virtual_units is None
            or position_units is None
            or position_units <= 0.0
            or parsed_virtual_units != position_units
        ):
            issues.append("INVALID_CLOSE_VIRTUAL_UNITS")
    if position_units == 0.0 and not entry_gate_action:
        issues.append("FLAT_BINDING_ONLY_ALLOWED_FOR_ENTRY_GATE")

    reason_code = proposal.get("reason_code")
    if not _is_exact_str(reason_code) or _REASON_CODE_RE.fullmatch(reason_code) is None:
        issues.append("INVALID_REASON_CODE")
    reason = proposal.get("reason")
    if (
        not _is_exact_str(reason)
        or not reason.strip()
        or len(reason) > MAX_REASON_CHARS
    ):
        issues.append("INVALID_REASON")

    sources = proposal.get("source_watermarks")
    if not isinstance(sources, list) or not 1 <= len(sources) <= MAX_SOURCE_WATERMARKS:
        issues.append("INVALID_SOURCE_WATERMARKS")
    else:
        source_ids: set[str] = set()
        previous_source_id: str | None = None
        for index, source in enumerate(sources):
            label = f"source_watermarks[{index}]"
            issues.extend(_source_watermark_issues(source, label=label, cutoff=cutoff))
            if isinstance(source, Mapping):
                source_id = source.get("source_id")
                if _is_exact_str(source_id):
                    if source_id in source_ids:
                        issues.append(f"DUPLICATE_SOURCE_ID:{source_id}")
                    source_ids.add(source_id)
                    if (
                        previous_source_id is not None
                        and source_id <= previous_source_id
                    ):
                        issues.append("SOURCE_WATERMARKS_NOT_CANONICALLY_SORTED")
                    previous_source_id = source_id

    identity = proposal.get("decision_identity_sha256")
    if not _is_sha256(identity):
        issues.append("INVALID_DECISION_IDENTITY_SHA256")
    elif verify_identity:
        try:
            computed_identity = inventory_decision_identity_sha256(proposal)
        except (TypeError, ValueError):
            computed_identity = None
        if computed_identity is None or identity != computed_identity:
            issues.append("DECISION_IDENTITY_SHA256_MISMATCH")
    return _dedupe(issues)


def _binding_issues(
    name: str,
    value: object,
    *,
    expected_keys: frozenset[str],
    cutoff: int | None,
    max_age_seconds: int | None,
) -> list[str]:
    issues: list[str] = []
    if not isinstance(value, Mapping):
        return [f"{name}:NOT_MAPPING"]
    try:
        binding = _snapshot_mapping(value, name)
    except ValueError:
        return [f"{name}:SNAPSHOT_UNREADABLE"]
    keys = _exact_string_keys(binding)
    for key in sorted(expected_keys - keys):
        issues.append(f"{name}:MISSING_FIELD:{key}")
    for key in sorted(keys - expected_keys):
        issues.append(f"{name}:UNKNOWN_FIELD:{key}")
    for key in sorted(expected_keys):
        if (key.endswith("_id") or key == "room_id") and not _is_identifier(
            binding.get(key)
        ):
            issues.append(f"{name}:INVALID_ID:{key}")
        if key.endswith("_sha256") and not _is_sha256(binding.get(key)):
            issues.append(f"{name}:INVALID_SHA256:{key}")
    if "sha256" in expected_keys and not _is_sha256(binding.get("sha256")):
        issues.append(f"{name}:INVALID_SHA256:sha256")
    observed = _parse_utc_nanoseconds(binding.get("observed_at_utc"))
    if observed is None:
        issues.append(f"{name}:INVALID_OBSERVED_AT_UTC")
    else:
        if binding.get("observed_at_utc") != _canonical_utc(observed):
            issues.append(f"{name}:NON_CANONICAL_OBSERVED_AT_UTC")
        if cutoff is not None:
            if observed > cutoff:
                issues.append(f"{name}:OBSERVED_AFTER_CUTOFF")
            elif (
                max_age_seconds is not None
                and cutoff - observed > max_age_seconds * 1_000_000_000
            ):
                issues.append(f"{name}:STALE_AT_CUTOFF")
    return issues


def _source_watermark_issues(
    value: object,
    *,
    label: str,
    cutoff: int | None,
) -> list[str]:
    if not isinstance(value, Mapping):
        return [f"{label}:NOT_MAPPING"]
    try:
        source = _snapshot_mapping(value, label)
    except ValueError:
        return [f"{label}:SNAPSHOT_UNREADABLE"]
    issues: list[str] = []
    keys = _exact_string_keys(source)
    for key in sorted(_SOURCE_WATERMARK_KEYS - keys):
        issues.append(f"{label}:MISSING_FIELD:{key}")
    for key in sorted(keys - _SOURCE_WATERMARK_KEYS):
        issues.append(f"{label}:UNKNOWN_FIELD:{key}")
    if not _is_identifier(source.get("source_id")):
        issues.append(f"{label}:INVALID_SOURCE_ID")
    if not _is_sha256(source.get("sha256")):
        issues.append(f"{label}:INVALID_SHA256")
    max_age = source.get("max_age_seconds")
    if not _is_exact_int(max_age) or not 1 <= max_age <= MAX_SOURCE_AGE_SECONDS:
        issues.append(f"{label}:INVALID_MAX_AGE_SECONDS")
        max_age = None
    watermark = _parse_utc_nanoseconds(source.get("watermark_at_utc"))
    if watermark is None:
        issues.append(f"{label}:INVALID_WATERMARK_AT_UTC")
    else:
        if source.get("watermark_at_utc") != _canonical_utc(watermark):
            issues.append(f"{label}:NON_CANONICAL_WATERMARK_AT_UTC")
        if cutoff is not None:
            if watermark > cutoff:
                issues.append(f"{label}:WATERMARK_AFTER_CUTOFF")
            elif (
                _is_exact_int(max_age) and cutoff - watermark > max_age * 1_000_000_000
            ):
                issues.append(f"{label}:STALE_AT_CUTOFF")
    return issues


def _proposal_timestamp_paths(
    proposal: Mapping[str, Any],
) -> list[tuple[dict[str, Any], str]]:
    paths: list[tuple[dict[str, Any], str]] = []
    if isinstance(proposal, dict):
        paths.append((proposal, "cutoff_at_utc"))
        paths.append((proposal, "expires_at_utc"))
    for name in (
        "session_binding",
        "policy_binding",
        "candidate_binding",
        "spec_binding",
        "lifecycle_binding",
        "ai_decision_binding",
        "ledger_binding",
        "state_binding",
        "snapshot_binding",
        "position_binding",
        "quote_binding",
    ):
        binding = proposal.get(name)
        if isinstance(binding, dict):
            paths.append((binding, "observed_at_utc"))
            if name == "ai_decision_binding":
                paths.append((binding, "produced_at_utc"))
    sources = proposal.get("source_watermarks")
    if isinstance(sources, list):
        for source in sources:
            if isinstance(source, dict):
                paths.append((source, "watermark_at_utc"))
    admission = proposal.get("admission_binding")
    if isinstance(admission, dict):
        entry_signal = admission.get("entry_signal")
        if isinstance(entry_signal, dict):
            paths.append((entry_signal, "observed_at_utc"))
        paths.append((admission, "permit_expires_at_utc"))
    return paths


def _decode_ledger_bytes(raw: bytes) -> tuple[list[dict[str, Any]], list[str]]:
    if not raw:
        return [], []
    issues: list[str] = []
    if not raw.endswith(b"\n"):
        issues.append("LEDGER_MISSING_TERMINAL_NEWLINE")
    lines = raw.splitlines()
    if len(lines) > MAX_LEDGER_ROWS:
        issues.append("LEDGER_ROW_LIMIT_EXCEEDED")
    rows: list[dict[str, Any]] = []
    for index, line in enumerate(lines, start=1):
        if not line:
            issues.append(f"BLANK_LEDGER_ROW:{index}")
            continue
        if len(line) > MAX_LEDGER_LINE_BYTES:
            issues.append(f"LEDGER_ROW_TOO_LARGE:{index}")
            continue
        try:
            decoded = json.loads(line)
        except (UnicodeDecodeError, json.JSONDecodeError):
            issues.append(f"INVALID_LEDGER_JSON:{index}")
            continue
        if not isinstance(decoded, dict):
            issues.append(f"LEDGER_ROW_NOT_OBJECT:{index}")
            continue
        rows.append(decoded)
    return rows, issues


def _validate_ledger_rows(
    rows: Sequence[dict[str, Any]],
    *,
    initial_issues: Sequence[str] = (),
) -> dict[str, Any]:
    issues = list(initial_issues)
    previous = GENESIS_DECISION_SHA256
    identities: set[str] = set()
    for index, row in enumerate(rows, start=1):
        for issue in validate_inventory_decision(row):
            issues.append(f"ROW_{index}:{issue}")
        if row.get("sequence") != index:
            issues.append(f"ROW_{index}:SEQUENCE_MISMATCH")
        if row.get("previous_decision_sha256") != previous:
            issues.append(f"ROW_{index}:PREVIOUS_SHA256_MISMATCH")
        identity = row.get("decision_identity_sha256")
        if _is_sha256(identity):
            if identity in identities:
                issues.append(f"ROW_{index}:DUPLICATE_DECISION_IDENTITY")
            identities.add(identity)
        row_sha = row.get("decision_sha256")
        if _is_sha256(row_sha):
            previous = row_sha
    terminal = previous if rows else None
    return _ledger_validation_result(issues, rows=rows, terminal_sha256=terminal)


def _ledger_validation_result(
    issues: Sequence[str],
    *,
    rows: Sequence[dict[str, Any]],
    terminal_sha256: str | None,
) -> dict[str, Any]:
    normalized = tuple(_dedupe(list(issues)))
    return {
        "contract": DOJO_AI_INVENTORY_DECISION_CONTRACT,
        "valid": not normalized,
        "issues": list(normalized),
        "row_count": len(rows),
        "terminal_decision_sha256": terminal_sha256,
        "paper_only": True,
        "order_authority": "NONE",
        "live_permission": False,
        "virtual_broker_mutation_allowed": True,
        "external_broker_mutation_allowed": False,
        "consumer_contract": DOJO_AI_INVENTORY_CONSUMER_CONTRACT,
        "decision_role": DOJO_AI_INVENTORY_DECISION_ROLE,
    }


def _find_identity(
    rows: Sequence[dict[str, Any]],
    identity: str,
) -> dict[str, Any] | None:
    for row in rows:
        if row.get("decision_identity_sha256") == identity:
            return row
    return None


def _proposal_projection(record: Mapping[str, Any]) -> dict[str, Any]:
    return {key: record.get(key) for key in _PROPOSAL_KEYS}


def _snapshot_mapping(value: Mapping[str, Any], label: str) -> dict[str, Any]:
    try:
        snapshot = dict(value)
    except Exception as exc:
        raise ValueError(f"{label} snapshot is unreadable") from exc
    if not all(_is_exact_str(key) for key in snapshot):
        raise ValueError(f"{label} keys must be exact strings")
    return snapshot


def _exact_string_keys(value: Mapping[object, object]) -> set[str]:
    return {key for key in value if _is_exact_str(key)}


def _canonical_json(value: object) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _canonical_sha256(value: object) -> str:
    return hashlib.sha256(_canonical_json(value).encode("utf-8")).hexdigest()


def _parse_utc_nanoseconds(value: object) -> int | None:
    if not _is_exact_str(value):
        return None
    matched = _UTC_RE.fullmatch(value)
    if matched is None:
        return None
    fraction = matched.group("fraction") or ""
    try:
        second = datetime.strptime(
            matched.group("seconds"), "%Y-%m-%dT%H:%M:%S"
        ).replace(tzinfo=timezone.utc)
    except ValueError:
        return None
    return int(second.timestamp()) * 1_000_000_000 + int(fraction.ljust(9, "0") or 0)


def _canonical_utc(epoch_nanoseconds: int) -> str:
    seconds, nanoseconds = divmod(epoch_nanoseconds, 1_000_000_000)
    base = datetime.fromtimestamp(seconds, tz=timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%S"
    )
    if nanoseconds:
        return f"{base}.{nanoseconds:09d}Z"
    return f"{base}Z"


def _datetime_from_canonical(value: str) -> datetime:
    parsed = _parse_utc_nanoseconds(value)
    if parsed is None:
        raise ValueError("timestamp is not canonical UTC")
    seconds, nanoseconds = divmod(parsed, 1_000_000_000)
    # ``datetime`` has microsecond precision.  Truncate sub-microsecond input
    # rather than using a float that could round a Sunday pre-open instant
    # across the weekly market boundary.
    return datetime.fromtimestamp(seconds, tz=timezone.utc).replace(
        microsecond=nanoseconds // 1_000
    )


def _datetime_to_canonical(value: datetime) -> str:
    if value.tzinfo is None:
        raise ValueError("writer clock must be timezone-aware")
    value = value.astimezone(timezone.utc)
    base = value.strftime("%Y-%m-%dT%H:%M:%S")
    if value.microsecond:
        return f"{base}.{value.microsecond:06d}Z"
    return f"{base}Z"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _finite_number(value: object) -> float | None:
    if value.__class__ not in {int, float}:
        return None
    parsed = float(value)
    return parsed if math.isfinite(parsed) else None


def _is_exact_str(value: object) -> bool:
    return value.__class__ is str


def _is_exact_int(value: object) -> bool:
    return value.__class__ is int


def _is_sha256(value: object) -> bool:
    return _is_exact_str(value) and _SHA256_RE.fullmatch(value) is not None


def _is_identifier(value: object) -> bool:
    return _is_exact_str(value) and _ID_RE.fullmatch(value) is not None


def _is_pair(value: object) -> bool:
    return _is_exact_str(value) and _PAIR_RE.fullmatch(value) is not None


def _dedupe(items: list[str]) -> list[str]:
    return list(dict.fromkeys(items))
