from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ISSUE_CODE = "GUARDIAN_RECEIPT_NOT_CONSUMED_BY_TRADER"
OPERATOR_REVIEW_ISSUE_CODE = "GUARDIAN_RECEIPT_NEEDS_OPERATOR_REVIEW"
BLOCK_NEW_ENTRY_CODE = "GUARDIAN_RECEIPT_NOT_CONSUMED_BY_TRADER_BLOCKS_NEW_ENTRY"

CONSUMED = "CONSUMED"
EXPIRED_ACKNOWLEDGED = "EXPIRED_ACKNOWLEDGED"
STALE_ACKNOWLEDGED = "STALE_ACKNOWLEDGED"
REJECTED_ACKNOWLEDGED = "REJECTED_ACKNOWLEDGED"
HISTORICAL_ONLY = "HISTORICAL_ONLY"
NEEDS_OPERATOR_REVIEW = "NEEDS_OPERATOR_REVIEW"

ACKNOWLEDGED_CLASSIFICATIONS = {
    CONSUMED,
    EXPIRED_ACKNOWLEDGED,
    STALE_ACKNOWLEDGED,
    REJECTED_ACKNOWLEDGED,
    HISTORICAL_ONLY,
}
CLASSIFICATIONS = ACKNOWLEDGED_CLASSIFICATIONS | {NEEDS_OPERATOR_REVIEW}


def load_guardian_receipt_consumption(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"_missing": True, "_path": str(path)}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"_missing": True, "_path": str(path), "_unreadable": True}
    if not isinstance(payload, dict):
        return {"_missing": True, "_path": str(path), "_unreadable": True}
    payload.setdefault("_path", str(path))
    return payload


def build_guardian_receipt_consumption(
    watchdog_payload: dict[str, Any] | None,
    *,
    now_utc: datetime | None = None,
    existing: dict[str, Any] | None = None,
    generated_by: str = "deterministic-preflight",
) -> dict[str, Any]:
    watchdog = watchdog_payload if isinstance(watchdog_payload, dict) else {}
    now = (now_utc or datetime.now(timezone.utc)).astimezone(timezone.utc)
    existing_by_key = {
        _classification_key(item): item
        for item in _classification_rows(existing)
        if _classification_key(item)
    }
    issues = _watchdog_guardian_issues(watchdog)
    rows: list[dict[str, Any]] = []
    for issue in issues:
        row = _classification_from_issue(
            issue,
            existing_by_key.get(_issue_key(issue)),
            generated_at_utc=now.isoformat(),
            generated_by=generated_by,
        )
        rows.append(row)
    normal_allowed = all(item.get("normal_routing_allowed") is True for item in rows)
    if not rows:
        status = "NO_GUARDIAN_RECEIPT_ISSUES"
        normal_allowed = True
    elif normal_allowed:
        status = "GUARDIAN_RECEIPT_ISSUES_ACKNOWLEDGED"
    else:
        status = "GUARDIAN_RECEIPT_OPERATOR_REVIEW_REQUIRED"
    return {
        "generated_at_utc": now.isoformat(),
        "status": status,
        "normal_routing_allowed": normal_allowed,
        "classifications": rows,
        "unresolved_issue_count": sum(1 for item in rows if item.get("normal_routing_allowed") is not True),
        "watchdog_generated_at_utc": watchdog.get("generated_at_utc"),
        "watchdog_status": watchdog.get("status"),
        "watchdog_path": (
            (watchdog.get("artifact_paths") or {}).get("output_json")
            if isinstance(watchdog.get("artifact_paths"), dict)
            else None
        ),
        "read_only": True,
        "live_side_effects": [],
    }


def write_guardian_receipt_consumption(
    payload: dict[str, Any],
    *,
    output_path: Path,
    report_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_guardian_receipt_consumption_report(payload), encoding="utf-8")


def render_guardian_receipt_consumption_report(payload: dict[str, Any]) -> str:
    lines = [
        "# Guardian Receipt Consumption Report",
        "",
        f"- Generated at UTC: `{payload.get('generated_at_utc')}`",
        f"- Status: `{payload.get('status')}`",
        f"- Normal routing allowed: `{payload.get('normal_routing_allowed')}`",
        f"- Read only: `{payload.get('read_only')}`",
        f"- Live side effects: `{len(payload.get('live_side_effects') or [])}`",
        "",
        "## Classifications",
        "",
    ]
    rows = _classification_rows(payload)
    if not rows:
        lines.append("- none")
    else:
        lines.extend(
            [
                "| Issue | Event | Action | Lifecycle | Consumed | Classification | Normal Routing | Generated By | Row Generated UTC | Reason |",
                "|---|---|---|---|---|---|---|---|---|---|",
            ]
        )
        for row in rows:
            reason = str(row.get("reason") or "").replace("|", "\\|")
            lines.append(
                f"| `{row.get('issue_code')}` | `{row.get('receipt_event_id')}` | "
                f"`{row.get('receipt_action')}` | `{row.get('receipt_lifecycle')}` | "
                f"`{row.get('consumed_by_trader')}` | `{row.get('classification')}` | "
                f"`{row.get('normal_routing_allowed')}` | `{row.get('generated_by')}` | "
                f"`{row.get('generated_at_utc')}` | {reason} |"
            )
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "- This artifact is a trader classification record only.",
            "- It does not consume the guardian receipt inside guardian-action-cycle.",
            "- It does not place orders, cancel orders, close positions, or change broker state.",
            "",
        ]
    )
    return "\n".join(lines)


def acknowledgement_for_receipt(
    consumption_payload: dict[str, Any],
    *,
    issue_code: str,
    receipt_event_id: str | None,
    receipt_action: str | None,
    receipt_lifecycle: str | None,
) -> dict[str, Any] | None:
    key = _key(issue_code, receipt_event_id, receipt_action, receipt_lifecycle)
    for row in _classification_rows(consumption_payload):
        if _classification_key(row) == key:
            return row
    return None


def consumption_status_summary(payload: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(payload, dict) or payload.get("_missing"):
        return {
            "status": "UNAVAILABLE",
            "normal_routing_allowed": None,
            "classifications": [],
            "unresolved_issue_count": 0,
            "missing": True,
            "path": payload.get("_path") if isinstance(payload, dict) else None,
        }
    rows = _classification_rows(payload)
    return {
        "status": payload.get("status"),
        "normal_routing_allowed": payload.get("normal_routing_allowed"),
        "classifications": rows,
        "unresolved_issue_count": payload.get("unresolved_issue_count"),
        "missing": False,
        "generated_at_utc": payload.get("generated_at_utc"),
        "watchdog_generated_at_utc": payload.get("watchdog_generated_at_utc"),
    }


def guardian_receipt_new_entry_blockers_from_paths(
    *,
    watchdog_path: Path | None = None,
    consumption_path: Path | None = None,
) -> list[dict[str, str]]:
    watchdog = _read_json_path(_env_path("QR_GUARDIAN_RECEIPT_WATCHDOG_PATH", watchdog_path))
    consumption = load_guardian_receipt_consumption(
        _env_path("QR_GUARDIAN_RECEIPT_CONSUMPTION_PATH", consumption_path)
    )
    return guardian_receipt_new_entry_blockers(watchdog, consumption)


def guardian_receipt_new_entry_blockers(
    watchdog_payload: dict[str, Any] | None,
    consumption_payload: dict[str, Any] | None,
) -> list[dict[str, str]]:
    issues = [
        issue
        for issue in _watchdog_guardian_issues(watchdog_payload if isinstance(watchdog_payload, dict) else {})
        if _issue_code(issue) in {ISSUE_CODE, OPERATOR_REVIEW_ISSUE_CODE}
    ]
    if not issues:
        return []
    blockers: list[dict[str, str]] = []
    for issue in issues:
        acknowledgement = acknowledgement_for_receipt(
            consumption_payload if isinstance(consumption_payload, dict) else {},
            issue_code=_issue_code(issue),
            receipt_event_id=_issue_event_id(issue),
            receipt_action=_issue_action(issue),
            receipt_lifecycle=_issue_lifecycle(issue),
        )
        if isinstance(acknowledgement, dict) and acknowledgement.get("normal_routing_allowed") is True:
            continue
        if isinstance(acknowledgement, dict):
            classification = str(acknowledgement.get("classification") or "UNKNOWN")
            reason = str(acknowledgement.get("reason") or "classification does not allow normal routing")
        else:
            classification = "UNCLASSIFIED"
            reason = "no matching guardian_receipt_consumption classification allows normal routing"
        blockers.append(
            {
                "code": BLOCK_NEW_ENTRY_CODE,
                "severity": "BLOCK",
                "message": (
                    f"{_issue_code(issue)} event={_issue_event_id(issue) or 'UNKNOWN'} "
                    f"action={_issue_action(issue) or 'UNKNOWN'} lifecycle={_issue_lifecycle(issue) or 'UNKNOWN'} "
                    f"classification={classification}: {reason}"
                ),
                "receipt_event_id": _issue_event_id(issue),
                "receipt_action": _issue_action(issue),
                "receipt_lifecycle": _issue_lifecycle(issue),
                "classification": classification,
            }
        )
    return blockers


def _classification_from_issue(
    issue: dict[str, Any],
    existing: dict[str, Any] | None,
    *,
    generated_at_utc: str,
    generated_by: str,
) -> dict[str, Any]:
    if isinstance(existing, dict):
        classification = str(existing.get("classification") or "").upper()
        if classification in CLASSIFICATIONS:
            row = dict(existing)
            row.setdefault("issue_code", _issue_code(issue))
            row.setdefault("receipt_event_id", _issue_event_id(issue))
            row.setdefault("receipt_action", _issue_action(issue))
            row.setdefault("receipt_lifecycle", _issue_lifecycle(issue))
            row.setdefault("consumed_by_trader", bool(issue.get("consumed_by_trader")))
            row.setdefault("generated_by", generated_by)
            row.setdefault("generated_at_utc", generated_at_utc)
            row["normal_routing_allowed"] = _normal_allowed_for_classification(classification)
            return row

    classification = _automatic_classification(issue)
    return {
        "issue_code": _issue_code(issue),
        "receipt_event_id": _issue_event_id(issue),
        "receipt_action": _issue_action(issue),
        "receipt_lifecycle": _issue_lifecycle(issue),
        "receipt_identity": issue.get("receipt_identity"),
        "receipt_source_paths": issue.get("receipt_source_paths") if isinstance(issue.get("receipt_source_paths"), list) else [],
        "consumed_by_trader": bool(issue.get("consumed_by_trader")),
        "classification": classification,
        "reason": _classification_reason(issue, classification),
        "normal_routing_allowed": _normal_allowed_for_classification(classification),
        "generated_by": generated_by,
        "generated_at_utc": generated_at_utc,
    }


def _automatic_classification(issue: dict[str, Any]) -> str:
    if issue.get("consumed_by_trader") is True:
        return CONSUMED
    if issue.get("emergency_or_margin_risk") is True:
        return NEEDS_OPERATOR_REVIEW
    lifecycle = _issue_lifecycle(issue)
    sources = [str(item) for item in (issue.get("receipt_sources") or []) if str(item)]
    if sources and "canonical" not in sources:
        return HISTORICAL_ONLY
    if lifecycle == "EXPIRED":
        return EXPIRED_ACKNOWLEDGED
    if lifecycle == "REJECTED":
        return REJECTED_ACKNOWLEDGED
    if issue.get("next_run_window_missed") is True or issue.get("expired_before_trader_run") is True:
        return STALE_ACKNOWLEDGED
    return NEEDS_OPERATOR_REVIEW


def _classification_reason(issue: dict[str, Any], classification: str) -> str:
    lifecycle = _issue_lifecycle(issue) or "UNKNOWN"
    action = _issue_action(issue) or "UNKNOWN"
    event_id = _issue_event_id(issue) or "UNKNOWN"
    if classification == CONSUMED:
        return f"Receipt event {event_id} {action} is already marked consumed_by_trader=true."
    if classification == HISTORICAL_ONLY:
        return f"Receipt event {event_id} {action} is archived-only; no current canonical receipt remains."
    if classification == EXPIRED_ACKNOWLEDGED:
        return f"Receipt event {event_id} {action} is lifecycle EXPIRED and was not consumed before expiry."
    if classification == STALE_ACKNOWLEDGED:
        return f"Receipt event {event_id} {action} is stale: lifecycle={lifecycle} and the next trader window was missed."
    if classification == REJECTED_ACKNOWLEDGED:
        return f"Receipt event {event_id} {action} is lifecycle REJECTED and is acknowledged as non-executable."
    return (
        f"Receipt event {event_id} {action} requires operator review before normal new-entry routing; "
        f"lifecycle={lifecycle}, severity={issue.get('severity')}."
    )


def _normal_allowed_for_classification(classification: str) -> bool:
    return classification in ACKNOWLEDGED_CLASSIFICATIONS


def _watchdog_guardian_issues(payload: dict[str, Any]) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    compact_issues = payload.get("guardian_receipt_issues")
    if isinstance(compact_issues, list):
        return [item for item in compact_issues if isinstance(item, dict)]
    guardian = payload.get("guardian_receipt") if isinstance(payload.get("guardian_receipt"), dict) else {}
    issues = guardian.get("issues") if isinstance(guardian.get("issues"), list) else []
    return [item for item in issues if isinstance(item, dict)]


def _env_path(name: str, fallback: Path | None) -> Path:
    raw = os.environ.get(name)
    if raw:
        return Path(raw)
    if fallback is not None:
        return fallback
    from quant_rabbit.paths import ROOT

    if name == "QR_GUARDIAN_RECEIPT_WATCHDOG_PATH":
        return ROOT / "data" / "qr_trader_run_watchdog.json"
    return ROOT / "data" / "guardian_receipt_consumption.json"


def _read_json_path(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _classification_rows(payload: dict[str, Any] | None) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        return []
    rows = payload.get("classifications")
    return [item for item in (rows if isinstance(rows, list) else []) if isinstance(item, dict)]


def _classification_key(row: dict[str, Any]) -> tuple[str, str, str, str]:
    return _key(
        row.get("issue_code"),
        row.get("receipt_event_id"),
        row.get("receipt_action"),
        row.get("receipt_lifecycle"),
    )


def _issue_key(issue: dict[str, Any]) -> tuple[str, str, str, str]:
    return _key(_issue_code(issue), _issue_event_id(issue), _issue_action(issue), _issue_lifecycle(issue))


def _key(
    issue_code: Any,
    receipt_event_id: Any,
    receipt_action: Any,
    receipt_lifecycle: Any,
) -> tuple[str, str, str, str]:
    normalized_issue_code = str(issue_code or ISSUE_CODE).upper()
    if normalized_issue_code == OPERATOR_REVIEW_ISSUE_CODE:
        normalized_issue_code = ISSUE_CODE
    return (
        normalized_issue_code,
        str(receipt_event_id or "").strip(),
        str(receipt_action or "").upper(),
        str(receipt_lifecycle or "").upper(),
    )


def _issue_code(issue: dict[str, Any]) -> str:
    return str(issue.get("code") or issue.get("issue_code") or ISSUE_CODE).upper()


def _issue_event_id(issue: dict[str, Any]) -> str:
    return str(issue.get("receipt_event_id") or issue.get("event_id") or "")


def _issue_action(issue: dict[str, Any]) -> str:
    return str(issue.get("receipt_action") or issue.get("action") or "").upper()


def _issue_lifecycle(issue: dict[str, Any]) -> str:
    return str(issue.get("receipt_lifecycle") or "").upper()
