from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ENV_LOCAL = ROOT / ".env.local"
DEFAULT_LEGACY_ARCHIVE = Path(
    os.environ.get(
        "QR_LEGACY_ARCHIVE",
        "/Users/tossaki/App/QuantRabbit_archives/QuantRabbit_legacy_20260430T151527Z",
    )
)
DEFAULT_HISTORY_DB = ROOT / "data" / "legacy_history.db"
DEFAULT_IMPORT_REPORT = ROOT / "docs" / "legacy_import_report.md"
DEFAULT_STRATEGY_PROFILE = ROOT / "data" / "strategy_profile.json"
DEFAULT_STRATEGY_REPORT = ROOT / "docs" / "strategy_mining_report.md"
DEFAULT_MARKET_STORY_PROFILE = ROOT / "data" / "market_story_profile.json"
DEFAULT_MARKET_STORY_REPORT = ROOT / "docs" / "market_story_report.md"
DEFAULT_MARKET_STATUS = ROOT / "data" / "market_status.json"
DEFAULT_MARKET_STATUS_REPORT = ROOT / "docs" / "market_status_report.md"
DEFAULT_CAMPAIGN_PLAN = ROOT / "data" / "daily_campaign_plan.json"
DEFAULT_CAMPAIGN_REPORT = ROOT / "docs" / "daily_campaign_report.md"
DEFAULT_TRADER_SETTINGS = ROOT / "data" / "trader_settings.json"
DEFAULT_TRADER_OVERRIDES = ROOT / "data" / "trader_overrides.json"
DEFAULT_ORDER_INTENTS = ROOT / "data" / "order_intents.json"
DEFAULT_ORDER_INTENT_REPORT = ROOT / "docs" / "order_intents_report.md"
DEFAULT_RECEIPT_PROMOTION_REPORT = ROOT / "docs" / "receipt_promotion_report.md"
DEFAULT_LIVE_ORDER_REQUEST = ROOT / "data" / "live_order_request.json"
DEFAULT_LIVE_ORDER_STAGE_REPORT = ROOT / "docs" / "live_order_stage_report.md"
DEFAULT_TRADER_DECISION = ROOT / "data" / "trader_decision.json"
DEFAULT_TRADER_DECISION_REPORT = ROOT / "docs" / "trader_decision_report.md"
DEFAULT_CODEX_TRADER_DECISION_RESPONSE = ROOT / "data" / "codex_trader_decision_response.json"
DEFAULT_TRADER_PROMPTS_DIR = ROOT / "docs" / "trader_prompts"
DEFAULT_POSITION_MANAGEMENT = ROOT / "data" / "position_management.json"
DEFAULT_POSITION_MANAGEMENT_REPORT = ROOT / "docs" / "position_management_report.md"
DEFAULT_POSITION_EXECUTION = ROOT / "data" / "position_execution.json"
DEFAULT_POSITION_EXECUTION_REPORT = ROOT / "docs" / "position_execution_report.md"
DEFAULT_PROFIT_PARTIAL_CLOSE = ROOT / "data" / "profit_partial_close.json"
DEFAULT_PROFIT_PARTIAL_CLOSE_REPORT = ROOT / "docs" / "profit_partial_close_report.md"
DEFAULT_PROFIT_PARTIAL_CLOSE_STATE = ROOT / "data" / "profit_partial_close_state.json"
DEFAULT_PREDICTIVE_LIMIT_ORDERS = ROOT / "data" / "predictive_limit_orders.json"
DEFAULT_BROKER_SNAPSHOT = ROOT / "data" / "broker_snapshot.json"
DEFAULT_DAILY_TARGET_STATE = ROOT / "data" / "daily_target_state.json"
DEFAULT_DAILY_TARGET_REPORT = ROOT / "docs" / "daily_target_report.md"
DEFAULT_REPLAY_BACKTEST = ROOT / "data" / "replay_backtest.json"
DEFAULT_REPLAY_BACKTEST_REPORT = ROOT / "docs" / "replay_backtest_report.md"
DEFAULT_AI_TEST_BOT_BACKTEST = ROOT / "data" / "ai_test_bot_backtest.json"
DEFAULT_AI_TEST_BOT_BACKTEST_REPORT = ROOT / "docs" / "ai_test_bot_backtest_report.md"
DEFAULT_OUTCOME_MART = ROOT / "data" / "outcome_mart.json"
DEFAULT_OUTCOME_MART_REPORT = ROOT / "docs" / "outcome_mart_report.md"
DEFAULT_AI_ATTACK_ADVICE = ROOT / "data" / "ai_attack_advice.json"
DEFAULT_AI_ATTACK_ADVICE_REPORT = ROOT / "docs" / "ai_attack_advice_report.md"
DEFAULT_GPT_TRADER_DECISION = ROOT / "data" / "gpt_trader_decision.json"
DEFAULT_GPT_TRADER_DECISION_REPORT = ROOT / "docs" / "gpt_trader_decision_report.md"
DEFAULT_COVERAGE_OPTIMIZATION = ROOT / "data" / "coverage_optimization.json"
DEFAULT_COVERAGE_OPTIMIZATION_REPORT = ROOT / "docs" / "coverage_optimization_report.md"
DEFAULT_POST_TRADE_LEARNING = ROOT / "data" / "post_trade_learning.json"
DEFAULT_POST_TRADE_LEARNING_REPORT = ROOT / "docs" / "post_trade_learning_report.md"
DEFAULT_LEARNING_AUDIT = ROOT / "data" / "learning_audit.json"
DEFAULT_LEARNING_AUDIT_REPORT = ROOT / "docs" / "learning_audit_report.md"
DEFAULT_FORECAST_HISTORY = ROOT / "data" / "forecast_history.jsonl"
DEFAULT_PROJECTION_LEDGER = ROOT / "data" / "projection_ledger.jsonl"
DEFAULT_ENTRY_THESIS_LEDGER = ROOT / "data" / "entry_thesis_ledger.jsonl"
DEFAULT_MEMORY_HEALTH = ROOT / "data" / "memory_health.json"
DEFAULT_MEMORY_HEALTH_REPORT = ROOT / "docs" / "memory_health_report.md"
DEFAULT_EXECUTION_REPLAY = ROOT / "data" / "execution_replay.json"
DEFAULT_EXECUTION_REPLAY_REPORT = ROOT / "docs" / "execution_replay_report.md"
DEFAULT_EXECUTION_LEDGER_DB = ROOT / "data" / "execution_ledger.db"
DEFAULT_EXECUTION_LEDGER_REPORT = ROOT / "docs" / "execution_ledger_report.md"
DEFAULT_VERIFICATION_LEDGER = ROOT / "data" / "verification_ledger.json"
DEFAULT_VERIFICATION_LEDGER_REPORT = ROOT / "docs" / "verification_ledger_report.md"
DEFAULT_DRY_RUN_CERTIFICATION = ROOT / "data" / "dry_run_certification.json"
DEFAULT_DRY_RUN_CERTIFICATION_REPORT = ROOT / "docs" / "dry_run_certification_report.md"
DEFAULT_COMPLETION_STATUS = ROOT / "data" / "completion_status.json"
DEFAULT_COMPLETION_STATUS_REPORT = ROOT / "docs" / "completion_status_report.md"
DEFAULT_PAIR_CHARTS = ROOT / "data" / "pair_charts.json"
DEFAULT_PAIR_CHARTS_REPORT = ROOT / "docs" / "pair_charts_report.md"
DEFAULT_CROSS_ASSET_SNAPSHOT = ROOT / "data" / "cross_asset_snapshot.json"
DEFAULT_CROSS_ASSET_REPORT = ROOT / "docs" / "cross_asset_report.md"
DEFAULT_FLOW_SNAPSHOT = ROOT / "data" / "flow_snapshot.json"
DEFAULT_FLOW_REPORT = ROOT / "docs" / "flow_report.md"
DEFAULT_CURRENCY_STRENGTH = ROOT / "data" / "currency_strength.json"
DEFAULT_CURRENCY_STRENGTH_REPORT = ROOT / "docs" / "currency_strength_report.md"
DEFAULT_LEVELS_SNAPSHOT = ROOT / "data" / "levels_snapshot.json"
DEFAULT_LEVELS_REPORT = ROOT / "docs" / "levels_report.md"
DEFAULT_CALENDAR_SNAPSHOT = ROOT / "data" / "economic_calendar.json"
DEFAULT_CALENDAR_REPORT = ROOT / "docs" / "economic_calendar_report.md"
DEFAULT_COT_SNAPSHOT = ROOT / "data" / "cot_snapshot.json"
DEFAULT_COT_REPORT = ROOT / "docs" / "cot_report.md"
DEFAULT_OPTION_SKEW = ROOT / "data" / "option_skew_snapshot.json"
DEFAULT_OPTION_SKEW_REPORT = ROOT / "docs" / "option_skew_report.md"
DEFAULT_NEWS_SNAPSHOT = ROOT / "data" / "news_items.json"
DEFAULT_NEWS_DIGEST = ROOT / "logs" / "news_digest.md"
DEFAULT_NEWS_FLOW_LOG = ROOT / "logs" / "news_flow_log.md"
# Append-only audit trail of every autotrade-cycle outcome. Each line is one
# JSONL event (one cycle) capturing decision, basket, execution result, and
# resulting trader-owned positions. AGENT_CONTRACT §6 / §11 require this
# trail; without it, post-trade review and `mine-strategy` have no signal.
DEFAULT_TRADER_JOURNAL = ROOT / "logs" / "trader_journal.jsonl"
