#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def row(name,v):return f"| {name} | {v['candidate_signals']} | {v['executed_cycles']} | {v['completed_cycles']} | {v['unresolved_inventory']} | {v['terminal_equity_jpy']:.2f} | {v['terminal_expectancy_per_execution_jpy']:.2f} | {v['median_time_to_target_seconds']/60:.1f} | {v['margin_occupancy_fraction']*100:.2f}% | {v['calendar_days_for_100_completed_cycles']:.1f} |"
def main():
 v1=json.loads((ROOT/"summary_all.json").read_text());v2=json.loads((ROOT/"confirmatory_v2/summary_all.json").read_text())
 lines=["# Operator-alpha OOS signal-supply readback","","Decision: **HOLD / entry trigger alone is insufficient.**","","The raw signal supply is abundant, but one target that never returns occupies the only concurrency slot and converts fast rotation into long inventory. End-of-replay losses were not forced closed; they remain executable-side MTM in terminal equity.","","## Diagnostic OOS — 2024 Q4","","Selected before outcome replay: `STRICT_PULLBACK_RECLAIM` (3,997 frozen signals).","","| Arm | Signals | Executed | Completed | Unresolved | Terminal equity JPY | Terminal exp/execution JPY | Median target min | Margin occupancy | Days/100 completions |","|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
 for a,x in v1['arms'].items():lines.append(row(a,x))
 lines += ["","## Confirmatory entry-only iteration — 2025 Q1","","Changed only entry: completed D1+H4 agreement, deep 0.25 ATR M1 pullback/reclaim, three completed S5 bodies, and one signal per pair/H4 bucket. The depth was chosen by supply only before outcome replay (729 frozen signals).","","| Arm | Signals | Executed | Completed | Unresolved | Terminal equity JPY | Terminal exp/execution JPY | Median target min | Margin occupancy | Days/100 completions |","|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
 for a,x in v2['arms'].items():lines.append(row(a,x))
 f=v2['arms']['FIXED_GROSS_500'];lines += ["","## Decisive conclusion","",f"- What works: strict higher-timeframe/S5-M1 signals exist ({f['signals_per_calendar_day']:.2f}/calendar day); fixed +500 completed {f['completed_cycles']} of {f['executed_cycles']} executions, and completed trades averaged {f['expectancy_per_completed_cycle_jpy']:.2f} JPY after costs.",f"- What fails: the remaining inventory is {f['terminal_unrealized_mtm_jpy']:.2f} JPY, terminal expectancy is {f['terminal_expectancy_per_execution_jpy']:.2f} JPY/execution, median target time is {f['median_time_to_target_seconds']/60:.1f} minutes, and the slot is occupied {f['margin_occupancy_fraction']*100:.2f}% of the period. Entry filtering did not remove the absorbing inventory state.","- Relative result: fixed +500 is the least-bad confirmatory arm by terminal equity, but no arm passes zero-unresolved or positive-terminal-expectancy gates.","- Concrete next change: keep this entry contract fixed and run a separately preregistered size/target-feasibility study using the observed manual 30k–38k unit range with a margin cap. At 5k units, gross +500 requires roughly six times the price move of 30k units, so this replay is not a faithful speed match to the manual executions. That next study must remain shadow/HOLD and may not hide unresolved MTM.","","Standard worker note: `scripts/replay_exit_workers_groups.py` is absent in this revision. The local runner preserves hard TP on, hard SL off, no end forced close, executable bid/ask, and `summary_all.json` as canonical output."]
 (ROOT/"readback_v1.md").write_text("\n".join(lines)+"\n");print("\n".join(lines));return 0
if __name__=="__main__":raise SystemExit(main())
